### PR TITLE
Fix HTML widget viewing on R 4.0 for Windows

### LINKED ISSUE #6737: Viewer Pane not working
### System details

    RStudio Edition :  Desktop
    RStudio Version :  1.2.5042
    OS Version      :  Windows 10 x64
    R Version       :  R version 4.0.0 (2020-04-24)

### Steps to reproduce the problem

Run any command that sends an interactive output to the Viewer pane.

For example,

``` r
library(mapview)
  
 mapview(breweries)
```
or
``` r
library(leaflet)

m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")
m  # Print the map
```

### Describe the problem in detail
The commands run without error but the Viewer pane remains blank (see screenshot below).

Note: running the same command from an R session in the terminal works fine.

image

### Describe the behavior you expected
In these specific examples, interactive maps should appear.

### Diagnostics Report
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/4536292/diagnostics-report.txt)

### (Potentially) Related Issues
#6381

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### PR DESCRIPTION
**Pull request by jmcphers**
In RStudio Desktop, we currently use R's HTTP server to serve files from the session temp folder, including HTML widgets. There appears to be a bug in this server in R 4.0 for Windows, which causes the widgets not to display and burns a bunch of CPU until R is restarted. See #6737 for the gory details.

This change is a minimal fix for the issue which is intended to work around this specific problem; it is intended for the RStudio 1.3 release. Consequently it only touches this specific combination (R 4.0, Windows). Since we already have a mechanism for serving these files in RStudio Server, we just use it in desktop mode when necessary.

We might consider a follow-up to change (for RStudio 1.4) which simplifies all this code by using our internal server all the time; I don't see any immediate advantage to proxying these requests to R but I could be missing something.

I also couldn't resist cleaning up some old tests for R < 3.0 which we no longer support.

Fixes #6737.

### CODE REVIEW

File: src/cpp/session/SessionModuleContext.cpp [hunk 1]
```diff
@@ -2390,7 +2390,24 @@ bool isSessionTempPath(FilePath filePath)
 
 std::string sessionTempDirUrl(const std::string& sessionTempPath)
 {
-   if (session::options().programMode() == kSessionProgramModeDesktop)
+   // In desktop mode we can have R itself handle requests for content in
+   // the session temporary folder.
+   bool useRHelpServer = session::options().programMode() == kSessionProgramModeDesktop;
```
Comment (kevinushey) [inline src/cpp/session/SessionModuleContext.cpp:2395]: nit: would it be worth making this a `static` and initialize it from a helper function? (since the value won't ever change in a given session)

**Comment by jmcphers** [comment]
>  I don't see any immediate advantage to proxying these requests to R but I could be missing something.

For posterity, I *was* missing something; there are a few regressions this change introduced. See #7118 for details.
