### PR TITLE
Fix opening project file in osx to fix #2203 and fix #2238

### LINKED ISSUE #2203: Opening .Rproj file does not open correct project
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.344
    OS Version      : macOS
    R Version       : 3.4.3

### Steps to reproduce the problem

* Start with no RStudio sessions running.
* In the Finder, open an .Rproj file to start RStudio with that project.
* In the Finder, open a different .Rprof file. A new RStudio window will open, but with the project opened in the previous step.

### LINKED ISSUE #2238: Double-clicking on associated text file (e.g. .R and .Rmd) opens RStudio but not the file
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.353
    OS Version      : Windows 10
    R Version       : 3.4.3

### Steps to reproduce the problem

Double-click on an file with a known R extension, e.g. .R or .Rmd, that is associated with RStudio.

### Describe the problem in detail

RStudio launches (as long as the file is associated with RStudio). However, the file isn't opened. Instead, RStudio starts up in the last state it was in, with the source pane showing the last tab/window in focus.

### Describe the behavior you expected

The file that was double-clicked should be opened and should be the focus in the source pane.

Note: this worked in 1.1.423, as well on Mac Desktop 1.2.353.

### PR DESCRIPTION
**Pull request by javierluraschi**
Fixes for #2203 and #2205. Project code assumes the last argument is the project name; therefore, this fix avoids appending more arguments at the very end. Somewhat related to https://github.com/rstudio/rstudio/commit/4350d5ea81c64b9d3f35d6a1deb9f42ee1f5012b but hard to catch since the relationship to the position was non-trivial.

### CODE REVIEW

File: src/cpp/desktop/DesktopMain.cpp [hunk 1]
```diff
@@ -298,7 +298,7 @@ int main(int argc, char* argv[])
          // get filename from command line arguments
          if (pApp->arguments().size() > 1)
          {
-            QString arg = pApp->arguments().last();
+            QString arg = pApp->arguments().at(1);
```
Comment (jmcphers) [inline src/cpp/desktop/DesktopMain.cpp]: This still relies on the file argument being in a particular position in order to be respected. I think this might be difficult to remember when invoking from elsewhere (we already broke it once!). Do you think it'd be worth removing the positional dependence by looking at the whole argument list?

Comment (javierluraschi) [reply src/cpp/desktop/DesktopMain.cpp]: I think is fine for some parameters to be positional, positional at the end is hard, but we can assume that `rstudio <file-to-open> [--run-diagnostics] [--disable-renderer-accessibility] [--disable-web-security]` is the expected launching call. We could add `--help` message as some point.

Comment (gtritchie) [reply src/cpp/desktop/DesktopMain.cpp]: FYI, Pro desktop does have --help (see DesktopOptionsPro.cpp).
