### PR TITLE
get testthat version only if TestFile/TestPackage

### LINKED ISSUE #10252: attempting to build package without testthat installed produces error in console
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.1.0.303
    OS Version      : macOS Monterey 12.1
    R Version       : R version 4.1.2 (2021-11-01)

### Steps to reproduce the problem

1. Create a new R Package project,
2. Ensure `testthat` is uninstalled (`remove.packages("testthat")`),
3. Try to build the package (`Cmd + Shift + B`).

### Describe the problem in detail

An error is printed to the console:

```
Error in packageVersion(pkg) : there is no package called 'testthat'
```

### Describe the behavior you expected

No error.

### PR DESCRIPTION
**Pull request by romainfrancois**
### Intent

closes #10252

### Approach

Delaying retrieving the version of testthat until we know we need it, i.e. when this is a build of type "TestFile" or "TestPackage". Getting the version directly in `testthatErrorParser()` rather than pass it in `testthatErrorParser`

```cpp
CompileErrorParser testthatErrorParser(const FilePath& basePath)
{
   core::Version testthatVersion;
   module_context::packageVersion("testthat", &testthatVersion);

   return boost::bind(parseTestThatErrors, basePath, _1, testthatVersion);
}
```

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

**Comment by romainfrancois** [comment]
I think that's fine for the description in #10252 but this probably needs to go further to deal with: 

 - attempt to test when no `tests/` directory. Doing a `<Test Package>` gives: 

image

but typing `devtools::test()` offers to create `tests/` : 

image

More interestingly when we accept, `devtools` follows up and offers to install `testthat`: 

image
 
Maybe this can be promoted to ui somehow.

File: src/cpp/session/modules/build/SessionBuild.cpp [hunk 1]
```diff
@@ -678,18 +678,20 @@ class Build : boost::noncopyable,
...
 
       // add testthat and shinytest result parsers
-      core::Version testthatVersion;
-      module_context::packageVersion("testthat", &testthatVersion);
-      
       if (type == kTestFile)
       {
          openErrorList_ = false;
-         parsers.add(testthatErrorParser(packagePath.getParent(), testthatVersion));
+         if (module_context::isPackageInstalled("testthat")) {
```
Comment (romainfrancois) [inline src/cpp/session/modules/build/SessionBuild.cpp:684]: Maybe we'd be better off with a method in `CompileErrorParsers`, i.e. `CompileErrorParsers::addTestthatErrorParser(<path>)` to avoid duplicating the `if` here.

**Review by kevinushey — APPROVED** [review]
LGTM!

Do you think the other issues re: presence of the `tests/` folder are worth tackling in this PR, or should we define a separate issue for that? (It seems like at a minimum, we should check whether the `tests/` folder exists and just bail with an error if it does not.)

**Comment by romainfrancois** [comment]
Thanks for the review. Another issue/pr is fine by me. At this point for me, this is mostly getting familiar with how things work. 

This might eventually be part of a bigger multi pr plan anyway, `devtools` related tools seem to make the difference between interactive and not, but it might be interesting to consider "non interactive but triggered from Rstudio" as another option. cc @jennybc.

**Comment by jmcphers** [comment]
@romainfrancois "closes" is a magic Github keyword, use "addresses" so that Github doesn't auto close the issue (we don't close issues until they're fully tested)

**Comment by jennybc** [comment]
> it might be interesting to consider "non interactive but triggered from Rstudio" as another option. cc @jennybc.

I'm intrigued. So, yes, happy to think on whether or how to make some devtools features that are behind a `base::interactive()` available in other contexts.

**Comment by romainfrancois** [comment]
Thanks @jmcphers I usually use `closes` so that the issue gets closed later when the pr is merged. I'll use addresses for future issues. 

@jennybc at this stage this is more wishful thinking related to getting familiar with the ide. I was thinking perhaps the ide could pop up a dialog serving the purpose of the `yesno("Create it?")`, or the code in `ui_todo('Setup testing with {ui_code("usethis::use_testthat()")}.')` could be marked as clickable somehow ?

Would it be worth greying out the "Test Package" menu when the testing infrastructure is not setup ? 

image

**Comment by kevinushey** [comment]
We use "Addresses:" rather than "Closes:" because we have a separate workflow with Codetree wherein an issue is closed on GitHub only after testing + QA verification has been completed.

For the record, I don't like it either (I don't think "closed in GitHub" should need to imply "closed in Codetree" but it's a limitation of the tool and so that's what we do.
