### PR TITLE
disable horizontal overflow for DataGrid

### LINKED ISSUE #4529: Horizontal scrollbar persists and hovers over modals
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1330
    OS Version      : MacOS 10.14.4
    R Version       : 3.5.2

### Steps to reproduce the problem

1. Close RStudio (so that we start fresh)
2. System Preferences -> General -> Show Scroll Bars -> Automatically (or When Scrolling etc.)
3. Open RStudio
4. Switch to Environment pane
5. Hover mouse over bottom of quadrant, right above the border
    - Horizontal scroll bar should appear
6. Click on another pane in the same quadrant
7. Click on Environment pane
    - Horizontal scroll bar is still gone

The kicker:

8. Hover mouse over bottom of Environment quadrant again, right above the border
    - Horizontal scroll bar should appear
9. Start opening an R Markdown file: File -> New File -> R Markdown
10. Make sure that the modal is at least somewhat over the environment pane; move it over if needed.
    - The scrollbar appears over the modal.

Follow that up with:

11. Click "Cancel."
12. Hover over the bottom of the pane, so that the scrollbar returns
13. System Preferences -> General -> Show Scroll Bars -> Always
     - Horizontal scroll is still there
14. Mouse over the Environment pane
     - Horizontal scroll bar may or may not go away
15. Switch to another pane in the same quadrant
16. Switch to Environment pane
     - Horizontal scroll bar may go away or be replaced by a lighter-gray scrollbar

Next:

17. Close RStudio
18. Reopen RStudio
19. Hover over bottom of Environment pane
     - No horizontal scroll bar

### Describe the problem in detail

The scrollbar in the Environment and Source panes (maybe more) sticks around when it shouldn't. It happens when you mouse over the area at the bottom of the pane, when System Preferences -> General -> Show Scroll Bars is set to "Automatically" or "When scrolling," but not "Always." 

more_scrolling

### Describe the behavior you expected

The scrollbar should go away, or at least it shouldn't appear over the modals.

### PR DESCRIPTION
**Pull request by kevinushey**
Closes #4529.

@jmcphers, to the best of my knowledge we don't ever actually want horizontal scrolling for any of the GWT DataGrids we use; we always show and resize columns such that they fill their container. For that reason, I think this PR should be safe, but can you think of any cases where this might not be true?

### CODE REVIEW

**Comment by jmcphers** [comment]
Not that I can think of!

File: src/gwt/src/org/rstudio/core/client/widget/RStudioDataGrid.java [hunk 1]
```diff
@@ -81,5 +82,23 @@ protected void onLoad()
...
+      // scroll bars. Since we don't ever require horizontal scrolling
+      // in the DataGrid objects we show, we just suppress horizontal
+      // overflow in any div element that does something with overflow.
+      //
+      // Again, this is something we'd normally do with CSS but because
+      // we need to perform surgery on arbitrary sub-divs which otherwise
+      // have no class we must resort to JavaScript + inline styles.
+      //
+      // https://github.com/rstudio/rstudio/issues/4529
+      children = DomUtils.querySelectorAll(parent, "div[style*='overflow:']");
```
Comment (jmcphers) [inline src/gwt/src/org/rstudio/core/client/widget/RStudioDataGrid.java]: Do we still need to surgically remove nodes from the DOM after this change? IIRC all of the flashing scrollbars we are trying to remove by surgical element removal are horizontal, so if we're suppressing horizontal overflow everywhere that may no longer be necessary.

Comment (kevinushey) [reply src/gwt/src/org/rstudio/core/client/widget/RStudioDataGrid.java]: Seems like it is no longer needed :-)

**Comment by kevinushey** [comment]
Merged to v1.2-patch and master.
