### PR TITLE
disallow attempts to open external URLs in iframes (closes #2756)

### LINKED ISSUE #2756: IFrames with external URLs pop up in separate windows
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.616
    OS Version      : macOS 10.13

### Steps to reproduce the problem

Run these two commands:

    > library(htmltools)
    > print(browse = TRUE, tags$iframe(src="https://www.rstudio.com/"))

### Describe the problem in detail

The `iframe` displays in the Viewer pane, but it's empty, and the RStudio.com website opens in a new browser window.

### Describe the behavior you expected

No external windows should be opened.

This regression occurred because QtWebEngine does not tell us what kind of `NavigationType` is being requested; we cannot distinguish between link clicks (which should indeed open external windows) and IFrame loads (which should not). 

https://github.com/rstudio/rstudio/blob/71ff50d204963610b4c338f912600e44d0ca3c0d/src/cpp/desktop/DesktopWebPage.cpp#L244-L252

We will need to distinguish between these cases in some other way.

### PR DESCRIPTION
**Pull request by kevinushey**
This is a second attempt at fixing #2756. The main difference here is that we're now careful to make sure the last intercepted URL is indeed associated with the attempted URL for navigation, and we deny attempts to load external URLs in iframes.

### CODE REVIEW

File: src/cpp/desktop/DesktopWebPage.cpp [hunk 1]
```diff
@@ -72,17 +72,12 @@ WebPage::WebPage(QUrl baseUrl, QWidget *parent, bool allowExternalNavigate) :
    defaultSaveDir_ = QDir::home();
    connect(this, SIGNAL(windowCloseRequested()), SLOT(closeRequested()));
    connect(profile(), &QWebEngineProfile::downloadRequested, onDownloadRequested);
+   connect(profile(), &WebProfile::urlIntercepted, this, &WebPage::onUrlIntercepted);
 }
 
 void WebPage::setBaseUrl(const QUrl& baseUrl)
 {
-   const WebProfile* pProfile = dynamic_cast<const WebProfile*>(profile());
```
Comment (kevinushey) [inline src/cpp/desktop/DesktopWebPage.cpp]: Since all of our `WebPage` implementations contain our own `WebProfile` implementation this code should be superfluous (let me know if I might be missing something)

Comment (jmcphers) [reply src/cpp/desktop/DesktopWebPage.cpp]: Yes, I think this should be okay -- when I wrote the `dynamic_cast` I couldn't convince myself 100% that this was the case, but we should know pretty quickly if it isn't!
