### PR TITLE
defend against unreliable mtime

### LINKED ISSUE #4312: Error in if (diff > 120) return("STALE") :  missing value where TRUE/FALSE needed
### System details
    RStudio Edition : Desktop
    RStudio Version : 1.2.1256
    OS Version      : Windows 10
    R Version       : 3.4.0 (2017-04-21) 

### Steps to reproduce the problem
When I open a saved project it prints to the console:
```
Error in if (diff > 120) return("STALE") : 
  missing value where TRUE/FALSE needed
Error in if (diff > 120) return("STALE") : 
  missing value where TRUE/FALSE needed
Error in if (diff > 120) return("STALE") : 
  missing value where TRUE/FALSE needed
Error in if (diff > 120) return("STALE") : 
  missing value where TRUE/FALSE needed
Error in if (diff > 120) return("STALE") : 
  missing value where TRUE/FALSE needed
```
### Describe the problem in detail
Googling for solutions shows the relevant line in `SessionPackages.R` where it does:
```
 info <- file.info(dir)
   diff <- difftime(Sys.time(), info$mtime, units = "secs")
   if (diff > 120)
      return("STALE")

```
when I run `file.info(getwd())` it returns:
```
                   size isdir mode mtime ctime atime exe
D:/users/me/R/test    0  TRUE  777  <NA>  <NA>  <NA>  no
```
so maybe an `NA` values in `info$mtime` are messing it up?
### Describe the behavior you expected
Doesn't appear to have any effect other than being a bit annoying.

Session info
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server x64 (build 14393)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.0  tools_3.4.0     packrat_0.4.8-1

### PR DESCRIPTION
**Pull request by kevinushey**
Attempts to access `mtime` may be unreliable -- in some cases, they can return `NA` if the modification time is either unknown or not available to the user for some reason.

To avoid this, we now serialize the current time as reported by `Sys.time()` when the directory is created, and use that in lieu of the `mtime` if it is unreadable for some reason.

Closes #4312.

### CODE REVIEW

File: src/cpp/session/modules/SessionPackages.R [hunk 1]
```diff
@@ -1429,7 +1429,16 @@ if (identical(as.character(Sys.info()["sysname"]), "Darwin") &&
...
    # to produce available.packages crashed or similar
    info <- file.info(dir)
-   diff <- difftime(Sys.time(), info$mtime, units = "secs")
+   time <- info$mtime
+   
+   # in some cases, mtime may not be available -- in that case, fall
+   # back to the time that was serialized when the process was launched
+   # https://github.com/rstudio/rstudio/issues/4312
+   if (is.na(time))
+      time <- readRDS(file.path(dir, "time.rds"))
```
Comment (jmcphers) [inline src/cpp/session/modules/SessionPackages.R]: Is there a pretty strong guarantee that the file exists and is readable at this point? (if not we might need a last-resort that just makes a safe assumption)

Comment (kevinushey) [reply src/cpp/session/modules/SessionPackages.R]: I can't imagine how the directory could exist without the associated `time.rds` file also existing (since they're created at the same time) but better safe than sorry -- I've added one final fallback that at least ensures that the user doesn't get polluted with warnings.
