### PR TITLE
fix issue with file monitor taking long time to shut down

### LINKED ISSUE #7117: RStudio Desktop slow to quit on Windows
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1019
    OS Version      : Windows-10 2004
    R Version       : 4.0.0

### Steps to reproduce the problem
- Start IDE on Windows, no source files open, no terminals, no project, etc.
- <kbd>Alt+F4</kbd> to quit (or via File / Quit, etc.)

### Describe the problem in detail
- Consistently takes about 3 seconds for RStudio to actually exit

### Describe the behavior you expected
- Exiting should be relatively instantaneous

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### PR DESCRIPTION
**Pull request by kevinushey**
When RStudio is initialized with a project, it registers a file monitor for that project. This entails scanning the files used within that project recursively, which can be slow for projects with many files (e.g. RStudio itself).

When we try to stop the file monitor, we were previously forced to wait for an in-flight registration to complete (or for 3 seconds, after which we just detached the thread and continued trying to exit).

This PR instead allows us to eagerly clean up and delete the context when a stop is requested. In case any completion requests are made after the context has been removed, we just check to see if the operation was aborted before attempting to access the associated context.

It seems like a lot of care was put into making sure the completion handler is the one to clean up the completion context struct, but I don't think this is necessary -- ultimately, the completion routine is just run on the same thread at an appropriate time, e.g. in response to `::SleepEx(..., TRUE)` as is done in the main thread's loop. We just need to check whether the completion routine was cancelled before attempting to run it.

Closes #7117.

### CODE REVIEW

**Comment by kevinushey** [comment]
Did some git surgery and re-targeted for v1.3.

File: src/cpp/core/system/file_monitor/Win32FileMonitor.cpp [hunk 1]
```diff
@@ -91,7 +93,8 @@ void safeCloseHandle(HANDLE hObject, const ErrorLocation& location)
    {
       if (!::CloseHandle(hObject))
       {
-         LOG_ERROR(LAST_SYSTEM_ERROR());
+         auto error = LAST_SYSTEM_ERROR();
+         core::log::logError(error, location);
```
Comment (gtritchie) [inline src/cpp/core/system/file_monitor/Win32FileMonitor.cpp:97]: Why the change from `LOG_ERROR` to direct logging call? I generally support reducing pre-proc macro usage as a Good Thing, but is there any other reason here?

File: src/cpp/core/system/PosixFileScanner.cpp [hunk 2]
```diff
@@ -124,6 +124,10 @@ Error scanFiles(const tree<FileInfo>::iterator_base& fromNode,
    // iterate over the names
    for (const std::string& name : names)
    {
+      // check for interrupt
+      if (boost::this_thread::interruption_requested())
+         return core::systemError(boost::system::errc::interrupted, ERROR_LOCATION);
```
Comment (gtritchie) [inline src/cpp/core/system/PosixFileScanner.cpp:129]: What are the expected consequences of this change for the non-Windows cases? Given this delay issue was Windows-specific, would it be safer to leave this part as-is and leave this change (potentially) for 1.4/master?

Thinking specifically of the QA test matrix; if code changes are definitively Windows-only, then (presumably) we can tell them to worry specifically only about Windows desktop with this change, but modifying this here seems to bring testing of Mac and Linux desktops into scope?

Comment (kevinushey) [reply src/cpp/core/system/PosixFileScanner.cpp:129]: I think ultimately other platforms run risking the same issue: the file monitor thread isn't able to clean up in time (because it's stuck in the file scanner), but we try to exit anyways and run into problems trying to shut down while the thread is still active.

That said, given that this is just theoretical and (AFAIK) we haven't observed this issue in v1.3 thus far, we could back this part out.

File: src/cpp/core/system/file_monitor/Win32FileMonitor.cpp (hunk 1 above)
Comment (kevinushey) [reply src/cpp/core/system/file_monitor/Win32FileMonitor.cpp:97]: The main reason was that the old version didn't use the `location` passed in from the caller.

File: src/cpp/core/system/file_monitor/Win32FileMonitor.cpp [hunk 3]
```diff
@@ -41,13 +42,15 @@ namespace {
 // buffer size for notifications (cannot be > 64kb for network drives)
 const std::size_t kBuffSize = 32768;
 
+// handle registry
+std::set<Handle> s_handleRegistry;
```
Comment (jmcphers) [inline src/cpp/core/system/file_monitor/Win32FileMonitor.cpp:46]: Do accesses to this registry require mutexes? (noticed they're all bare; haven't looked too closely but I know file monitors run on a thread)

Comment (kevinushey) [reply src/cpp/core/system/file_monitor/Win32FileMonitor.cpp:46]: I think you're right: these actions can be triggered either by the main thread, or by the file monitor thread itself. For example, `registerMonitor()` is typically called by the main thread, whereas `unregisterMonitor()` here is being called by the thread itself.

A race here should be unlikely since registration normally only ever happens at startup, and de-registration on quit / shutdown, but one could imagine the potential in session that quickly close / exit for some reason.

**Comment by jmcphers** [comment]
FYI, rebasing to 1.3 since Giant Goldenrod merge has occurred.

**Comment by R-Hannibal** [comment]
@gtritchie + @kevinushey - Following up on the comment/discussion [HERE](https://github.com/rstudio/rstudio/pull/7343#pullrequestreview-448358607), is there anything outside of the baseline Windows desktop fix that we should test before considering this issue as verified (fix is looking successful on the latest preview, but I've only tested Windows desktop)?

Also wanted to make sure that [NEWS ](https://github.com/rstudio/rstudio/blob/master/NEWS.md)gets updated as needed and I'm not currently seeing an entry for this fix. Am I looking in the right place/should this issue in fact have a news entry?

**Comment by kevinushey** [comment]
NEWS was updated here: https://github.com/rstudio/rstudio/commit/ec16b5e3237cfe0daa0282a7456021d551139af7

I don't think there's anything else that needs to be tested; the main thing to keep an eye out for would be if we happened to see RStudio crashing on exit in some circumstances. Fortunately that doesn't appear to be happening!
