### PR TITLE
List target build OS in version command and about dialog

### LINKED ISSUE #5862: Report Linux host platform in rstudio-server version and About
A common problem on Linux platforms is that users download a binary for the wrong platform, which results in a binary that will install, but doesn't run, or doesn't run correctly. 

For example, the Ubuntu 14 binary can be installed on Ubuntu 18, but will incur some issues with OpenSSL since it uses OpenSSL 1.0, and won't support e.g. TLS 1.3. 

However, we currently have no way to introspect an installed binary to see which platform it was targeting. So if a customer is having trouble on Ubuntu 18, we have literally no way to tell if they installed the Ubuntu 14 binary or the Ubuntu 18  binary (without some very convoluted forensics). We are thus often obligated to advise that they reinstall the correct version just in case. 

It feels too heavy handed (and error prone) to try to filter this in our pre-installation script by blocking known-problematic installs entirely, but we could dramatically improve our ability to troubleshoot these kinds of issues by including the build host OS in:

1. The output of `rstudio-server version`,
2. The diagnostics report, and 
3. The Help/About dialog.

### PR DESCRIPTION
**Pull request by kfeinauer**
Closes #5862

### CODE REVIEW

File: src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogContents.java [hunk 1]
```diff
@@ -62,7 +62,7 @@ private AboutDialogContents()
    public AboutDialogContents(ProductInfo info, ProductEditionInfo editionInfo)
    {
       initWidget(uiBinder.createAndBindUi(this));
-      versionLabel.setText(info.version);
+      versionLabel.setText(info.version + "for " + info.os);
```
Comment (jmcphers) [inline src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogContents.java]: I think making it part of the version number here will emphasize it more than is necessary. Let's put it in the build info along with the release name and commit hash.

File: Jenkinsfile [hunk 2]
```diff
@@ -154,20 +157,20 @@ messagePrefix = "Jenkins ${env.JOB_NAME} build: <${env.BUILD_URL}display/redirec
...
-          [os: 'centos7',    arch: 'x86_64', flavor: 'desktop', variant: ''],
-          [os: 'xenial',     arch: 'amd64',  flavor: 'server',  variant: ''],
-          [os: 'xenial',     arch: 'amd64',  flavor: 'desktop', variant: ''],
-          [os: 'bionic',     arch: 'amd64',  flavor: 'server',  variant: ''],
-          [os: 'bionic',     arch: 'amd64',  flavor: 'desktop', variant: ''],
-          [os: 'debian9',    arch: 'x86_64', flavor: 'server',  variant: ''],
-          [os: 'debian9',    arch: 'x86_64', flavor: 'desktop', variant: ''],
-          [os: 'centos8',   arch: 'x86_64', flavor: 'server',  variant: ''],
-          [os: 'centos8',   arch: 'x86_64', flavor: 'desktop', variant: '']
+          [os: 'centos6',    arch: 'x86_64', flavor: 'server',  variant: '',    package_os: 'CentOS 6'],
```
Comment (jmcphers) [inline Jenkinsfile]: Clever, I poked around at an approach for making this change and stalled out because I couldn't find a non-gross way to get the host OS to emit its own release name. This is a lot tidier!

File: Jenkinsfile [hunk 3]
```diff
@@ -154,20 +157,20 @@ messagePrefix = "Jenkins ${env.JOB_NAME} build: <${env.BUILD_URL}display/redirec
...
+          [os: 'opensuse',   arch: 'x86_64', flavor: 'server',  variant: '',    package_os: 'OpenSUSE'],
+          [os: 'opensuse',   arch: 'x86_64', flavor: 'desktop', variant: '',    package_os: 'OpenSUSE 15'],
```
Comment (kevinushey) [inline Jenkinsfile]: Double-checking; should this be OpenSUSE or OpenSUSE 15?

Comment (kfeinauer) [reply Jenkinsfile]: Yes, thanks. I'll update this on master.
