### PR TITLE
check for overflow when casting JSON to R integer vector

### LINKED ISSUE #5725: Assert / Abnormal session shutdown previewing a (r)markdown file in debug build
### System details

    RStudio Edition : Desktop or Server (debug build)
    RStudio Version : master, 1.3.595 equivalent
    OS Version      : macOS (dev server)
    R Version       : 3.6.0

### Steps to reproduce the problem
- start IDE
- create a new text file, type "hello", save as "mark.md"
- click Preview to render as HTML

### Describe the problem in detail
- no preview, and get

### Describe the behavior you expected
- preview of markdown file
- also crashes when I try to Knit an RMarkdown file

### Callstack
- possibly related to 29f44e7f
- attached debugger to rsession, and clicked "Preview", an assert fails (thus the crash)

```
__assert_rtn 0x00007fff6d38ecd6
rstudio::core::json::Value::getInt() const Json.cpp:443
rstudio::r::sexp::create(rstudio::core::json::Value const&, rstudio::r::sexp::Protect*) RSexp.cpp:922
rstudio::r::sexp::create(rstudio::core::json::Object const&, rstudio::r::sexp::Protect*) RSexp.cpp:1016
rstudio::session::source_database::SourceDocument::toRObject(rstudio::r::sexp::Protect*, bool) const SessionSourceDatabase.cpp:562
rstudio::session::source_database::(anonymous namespace)::rs_getDocumentProperties(SEXPREC*, SEXPREC*) SessionSourceDatabase.cpp:1022
R_doDotCall 0x000000010d09091b
do_dotcall 0x000000010d0927b3
Rf_eval 0x000000010d0c1fab
do_begin 0x000000010d0e2a20
Rf_eval 0x000000010d0c1ce0
R_execClosure 0x000000010d0e03a9
Rf_applyClosure 0x000000010d0df2aa
Rf_eval 0x000000010d0c201d
do_set 0x000000010d0e35bd
Rf_eval 0x000000010d0c1ce0
do_begin 0x000000010d0e2a20
Rf_eval 0x000000010d0c1ce0
R_execClosure 0x000000010d0e03a9
Rf_applyClosure 0x000000010d0df2aa
Rf_eval 0x000000010d0c201d
protectedEval 0x000000010d07d0d4
R_ToplevelExec 0x000000010d07cfac
R_tryEval 0x000000010d07d07c
rstudio::r::exec::(anonymous namespace)::evaluateExpressionsUnsafe(SEXPREC*, SEXPREC*, SEXPREC**, rstudio::r::sexp::Protect*, rstudio::r::exec::(anonymous namespace)::EvalType) RExec.cpp:154
rstudio::r::exec::(anonymous namespace)::evaluateExpressions(SEXPREC*, SEXPREC*, SEXPREC**, rstudio::r::sexp::Protect*) RExec.cpp:187
rstudio::r::exec::RFunction::call(SEXPREC*, bool, SEXPREC**, rstudio::r::sexp::Protect*) RExec.cpp:422
rstudio::r::exec::RFunction::call(SEXPREC*, SEXPREC**, rstudio::r::sexp::Protect*) RExec.cpp:384
rstudio::core::Error rstudio::r::exec::RFunction::call<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(SEXPREC*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) RExec.hpp:233
rstudio::core::Error rstudio::r::exec::RFunction::call<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) RExec.hpp:224
rstudio::session::modules::rmarkdown::(anonymous namespace)::RenderRmd::start(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) SessionRMarkdown.cpp:451
rstudio::session::modules::rmarkdown::(anonymous namespace)::RenderRmd::create(rstudio::core::FilePath const&, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) SessionRMarkdown.cpp:361
rstudio::session::modules::rmarkdown::(anonymous namespace)::doRenderRmd(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, rstudio::core::json::JsonRpcResponse*) SessionRMarkdown.cpp:974
rstudio::session::modules::rmarkdown::(anonymous namespace)::renderRmd(rstudio::core::json::JsonRpcRequest const&, rstudio::core::json::JsonRpcResponse*) SessionRMarkdown.cpp:1049
rstudio_boost::detail::function::function_invoker2<rstudio::core::Error (*)(rstudio::core::json::JsonRpcRequest const&, rstudio::core::json::JsonRpcResponse*), rstudio::core::Error, rstudio::core::json::JsonRpcRequest const&, rstudio::core::json::JsonRpcResponse*>::invoke(rstudio_boost::detail::function::function_buffer&, rstudio::core::json::JsonRpcRequest const&, rstudio::core::json::JsonRpcResponse*) function_template.hpp:100
rstudio_boost::function2<rstudio::core::Error, rstudio::core::json::JsonRpcRequest const&, rstudio::core::json::JsonRpcResponse*>::operator()(rstudio::core::json::JsonRpcRequest const&, rstudio::core::json::JsonRpcResponse*) const function_template.hpp:763
rstudio::core::json::(anonymous namespace)::runSynchronousFunction(rstudio_boost::function<rstudio::core::Error (rstudio::core::json::JsonRpcRequest const&, rstudio::core::json::JsonRpcResponse*)> const&, rstudio::core::json::JsonRpcRequest const&, rstudio_boost::function<void (rstudio::core::Error const&, rstudio::core::json::JsonRpcResponse*)> const&) JsonRpc.cpp:447
void rstudio_boost::_bi::list3<rstudio_boost::_bi::value<rstudio_boost::function<rstudio::core::Error (rstudio::core::json::JsonRpcRequest const&, rstudio::core::json::JsonRpcResponse*)> >, rstudio_boost::arg<1>, rstudio_boost::arg<2> >::operator()<void (*)(rstudio_boost::function<rstudio::core::Error (rstudio::core::json::JsonRpcRequest const&, rstudio::core::json::JsonRpcResponse*)> const&, rstudio::core::json::JsonRpcRequest const&, rstudio_boost::function<void (rstudio::core::Error const&, rstudio::core::json::JsonRpcResponse*)> const&), rstudio_boost::_bi::rrlist2<rstudio::core::json::JsonRpcRequest const&, rstudio_boost::function<void (rstudio::core::Error const&, rstudio::core::json::JsonRpcResponse*)> const&> >(rstudio_boost::_bi::type<void>, void (*&)(rstudio_boost::function<rstudio::core::Error (rstudio::core::json::JsonRpcRequest const&, rstudio::core::json::JsonRpcResponse*)> const&, rstudio::core::json::JsonRpcRequest const&, rstudio_boost::function<void (rstudio::core::Error const&, rstudio::core::json::JsonRpcResponse*)> const&), rstudio_boost::_bi::rrlist2<rstudio::core::json::JsonRpcRequest const&, rstudio_boost::function<void (rstudio::core::Error const&, rstudio::core::json::JsonRpcResponse*)> const&>&, int) bind.hpp:398
void rstudio_boost::_bi::bind_t<void, void (*)(rstudio_boost::function<rstudio::core::Error (rstudio::core::json::JsonRpcRequest const&, rstudio::core::json::JsonRpcResponse*)> const&, rstudio::core::json::JsonRpcRequest const&, rstudio_boost::function<void (rstudio::core::Error const&, rstudio::core::json::JsonRpcResponse*)> const&), rstudio_boost::_bi::list3<rstudio_boost::_bi::value<rstudio_boost::function<rstudio::core::Error (rstudio::core::json::JsonRpcRequest const&, rstudio::core::json::JsonRpcResponse*)> >, rstudio_boost::arg<1>, rstudio_boost::arg<2> > >::operator()<rstudio::core::json::JsonRpcRequest const&, rstudio_boost::function<void (rstudio::core::Error const&, rstudio::core::json::JsonRpcResponse*)> const&>(rstudio::core::json::JsonRpcRequest const&, rstudio_boost::function<void (rstudio::core::Error const&, rstudio::core::json::JsonRpcResponse*)> const&) bind.hpp:1318
rstudio_boost::detail::function::void_function_obj_invoker2<rstudio_boost::_bi::bind_t<void, void (*)(rstudio_boost::function<rstudio::core::Error (rstudio::core::json::JsonRpcRequest const&, rstudio::core::json::JsonRpcResponse*)> const&, rstudio::core::json::JsonRpcRequest const&, rstudio_boost::function<void (rstudio::core::Error const&, rstudio::core::json::JsonRpcResponse*)> const&), rstudio_boost::_bi::list3<rstudio_boost::_bi::value<rstudio_boost::function<rstudio::core::Error (rstudio::core::json::JsonRpcRequest const&, rstudio::core::json::JsonRpcResponse*)> >, rstudio_boost::arg<1>, rstudio_boost::arg<2> > >, void, rstudio::core::json::JsonRpcRequest const&, rstudio_boost::function<void (rstudio::core::Error const&, rstudio::core::json::JsonRpcResponse*)> const&>::invoke(rstudio_boost::detail::function::function_buffer&, rstudio::core::json::JsonRpcRequest const&, rstudio_boost::function<void (rstudio::core::Error const&, rstudio::core::json::JsonRpcResponse*)> const&) function_template.hpp:158
rstudio_boost::function2<void, rstudio::core::json::JsonRpcRequest const&, rstudio_boost::function<void (rstudio::core::Error const&, rstudio::core::json::JsonRpcResponse*)> const&>::operator()(rstudio::core::json::JsonRpcRequest const&, rstudio_boost::function<void (rstudio::core::Error const&, rstudio::core::json::JsonRpcResponse*)> const&) const function_template.hpp:763
rstudio::session::rpc::handleRpcRequest(rstudio::core::json::JsonRpcRequest const&, rstudio_boost::shared_ptr<rstudio::session::HttpConnection>, rstudio::session::http_methods::ConnectionType) SessionRpc.cpp:274
rstudio::session::http_methods::handleConnection(rstudio_boost::shared_ptr<rstudio::session::HttpConnection>, rstudio::session::http_methods::ConnectionType) SessionHttpMethods.cpp:779
rstudio::session::http_methods::waitForMethod(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, rstudio_boost::function<void ()> const&, rstudio_boost::function<bool ()> const&, rstudio::core::json::JsonRpcRequest*) SessionHttpMethods.cpp:531
rstudio::session::console_input::rConsoleRead(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, rstudio::r::session::RConsoleInput*) SessionConsoleInput.cpp:194
rstudio_boost::detail::function::function_invoker3<bool (*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, rstudio::r::session::RConsoleInput*), bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, rstudio::r::session::RConsoleInput*>::invoke(rstudio_boost::detail::function::function_buffer&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, rstudio::r::session::RConsoleInput*) function_template.hpp:100
rstudio_boost::function3<bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, rstudio::r::session::RConsoleInput*>::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, rstudio::r::session::RConsoleInput*) const function_template.hpp:763
rstudio::r::session::RReadConsole(char const*, unsigned char*, int, int) RStdCallbacks.cpp:317
Rf_ReplIteration 0x000000010d111ec6
run_Rmainloop 0x000000010d1136af
run_Rmainloop 0x000000010d113646
rstudio::r::session::runEmbeddedR(rstudio::core::FilePath const&, rstudio::core::FilePath const&, bool, bool, SA_TYPE, rstudio::r::session::Callbacks const&, rstudio::r::session::InternalCallbacks*) REmbeddedPosix.cpp:152
rstudio::r::session::run(rstudio::r::session::ROptions const&, rstudio::r::session::RCallbacks const&) RSession.cpp:371
main SessionMain.cpp:2109
```

### PR DESCRIPTION
**Pull request by kevinushey**
Closes #5725.

### CODE REVIEW

File: src/cpp/r/RSexp.cpp [hunk 1]
```diff
@@ -909,7 +909,32 @@ SEXP create(SEXP valueSEXP, Protect* pProtect)
...
 }
+
+namespace {
+
+template <typename T>
+SEXP createInteger(const core::json::Value& value, Protect* pProtect)
+{
+   T innerValue = value.getValue<T>();
+   
+   bool overflow =
```
Comment (kevinushey) [inline src/cpp/r/RSexp.cpp]: Maybe worth having a helper in `SafeConvert` that uses `gsl::narrow_cast`?

File: src/cpp/r/RSexp.cpp [hunk 2]
```diff
@@ -919,7 +944,26 @@ SEXP create(const core::json::Value& value, Protect* pProtect)
...
+      {
+         return createInteger<unsigned>(value, pProtect);
+      }
+      else if (value.isInt())
+      {
+         return createInteger<int>(value, pProtect);
+      }
+      else
+      {
+         assert(false);
```
Comment (gtritchie) [inline src/cpp/r/RSexp.cpp]: Per our conversation can we log an error here?
