### PR TITLE
Don't suspend sessions with external pointers (fixes #1696)

### LINKED ISSUE #1696: Suppress session suspension when external pointers are present in the global environment
R objects can include external pointers. When these are present in the global environment, RStudio should suppress the automatic session suspension which would ordinarily occur; the external pointers cannot be restored, so when the session resumes after suspension, those objects which contain them will not work, and may cause crashes or instability.

### PR DESCRIPTION
**Pull request by jmcphers**
This change prevents sessions from suspending when they have active external pointer objects.

This more or less duplicates some existing R code which looked for the opposite case (`NULL` external pointers). This has been rewritten in C for efficiency, and updated to search inside environments as well as S4 objects.

### CODE REVIEW

File: src/cpp/session/modules/SessionEnvironment.R [hunk 1]
```diff
@@ -432,7 +432,7 @@
    obj <- get(objName, env)
    # objects containing null external pointers can crash when
    # evaluated--display generically (see case 4092)
-   hasNullPtr <- .rs.hasNullExternalPointer(obj)
+   hasNullPtr <- .Call("rs_hasExternalPointer", obj, TRUE)
```
Comment (kevinushey) [inline src/cpp/session/modules/SessionEnvironment.R]: You might want to specify `PACKAGE = "(embedding)"` as otherwise R will search through all loaded DLLs for this routine and this is often slow. Since we're calling this on a potentially large environment it's worth being explicit there.

File: src/cpp/session/modules/environment/SessionEnvironment.cpp [hunk 2]
```diff
@@ -112,6 +112,57 @@ bool handleRBrowseEnv(const core::FilePath& filePath)
...
+
+   return false;
+}
+
+SEXP rs_hasExternalPointer(SEXP objSEXP, SEXP nullSEXP)
+{
+   bool nullPtr = r::sexp::asLogical(nullSEXP);
+   r::sexp::Protect protect;
+   bool hasPtr = false;
+   if (r::sexp::isExternalPointer(objSEXP))
```
Comment (kevinushey) [inline src/cpp/session/modules/environment/SessionEnvironment.cpp]: Should we be checking S4 objects here as well? (the previous implementation recursed into S4 objects but not environments; it seems like we should really be doing both)

File: src/cpp/session/modules/environment/SessionEnvironment.cpp [hunk 3]
```diff
@@ -112,6 +112,57 @@ bool handleRBrowseEnv(const core::FilePath& filePath)
...
 }
 
+bool hasExternalPtr(SEXP env,      // environment to search for external pointers
+                    bool nullPtr,  // whether to look for NULL pointers 
+                    int level = 5) // maximum recursion depth (envs can have self-ref loops)
+{
+   // list the contents of this environment
+   std::vector<r::sexp::Variable> vars;
+   r::sexp::Protect rProtect;
+   r::sexp::listEnvironment(env,
```
Comment (kevinushey) [inline src/cpp/session/modules/environment/SessionEnvironment.cpp]: This will blow up if the object happens to be an S4 object subclassing `"environment"` -- you might want to validate with e.g. `sexp::isPrimitiveEnvironment()`; our implementation of `listEnvironment()` should probably become S4-object aware as well (but unfortunately interacting with S4 objects at the C / C++ level is tough).

**Comment by kevinushey** [comment]
Since S4 slots are really just attributes, we could gain a bit more fidelity by recursing into the attributes of R objects as well (perhaps scoping this to just S4 objects to reflect the prior behavior).

**Comment by jmcphers** [comment]
Thanks for catching that, I misread this:

https://github.com/rstudio/rstudio/blob/c4c3639f023f2d4cbf5b05ac75e116d18f897719/src/cpp/r/RSexp.cpp#L598-L610

and presumed that S4 objects would generally be treated as environments (as always, the truth is more complicated!). I'll follow up with a change that inspects both.

**Comment by jmcphers** [comment]
@kevinushey Think I've captured all your feedback, let me know if anything still looks amiss!

**Comment by kevinushey** [comment]
Looks good to me! I'll let you merge when ready.
