### PR TITLE
Check for write permissions before performing a global replace

### LINKED ISSUE #6048: File properties aren't respected by global find and replace
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.3.743 & 1.3.730
    OS Version      : MacOS 10.15.3 & Red Hat 7.8
    R Version       : 3.6.1 & 3.6.0

### Steps to reproduce the problem

1. Create a file called `mischief.R` containing just one line, `Loki`.
2. On the command line: change the file permissions to read-only and a different (real) owner and group, e.g.
```
chmod 444 mishchief.R
chown another_user mishchief.R
chgrp another_group mishchief.R
```
3. Make sure that the permissions, owner, and group have been updated correctly, e.g.
```
# ls -l mischief.R 
-r--r--r--. 1 another_user another_group 5 Jan 17 18:58 mischief.R
```
3. In the IDE: Edit -> Find in Files
4. Under "Find" type `Loki`
5. Under "Search In" choose the directory containing the file `mischief.R`
6. Click on "Find"
    - The search should display the file name and location above, with _Loki_ highlighted in the matching lines
7. Next to "Replace With" type `Trickster`
8. Replace All -> Yes
    - The search should display the file name and location above, with _Trickster_ highlighted in the matching lines
9. On the command line, check the permissions, etc., on the file
    - Write permissions have been added to the file, and the owner and group have reverted to the user and group associated with the RStudio account
```
# ls -l mischief.R 
-rw-rw-r--. 1 rstudio rstudio 5 Jan 17 18:58 mischief.R
```
10. Check the contents of the file: _Loki_ is replaced with _Trickster_
```
[root@ip-10-0-0-42 global]# cat mischief.R 
Trickster
```

### Describe the problem in detail

The file has been updated, and its permissions, owner, and group have been changed.

### Describe the behavior you expected

The existing file properties should be respected:
1. File permissions, owner, and group should not be changed.
2. The file should not be changed, as it's not supposed to be writable.

----------

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### PR DESCRIPTION
**Pull request by melissa-barca**
Fixes #6048 

Global replace functionality works by copying the contents of the initial file to a temporary file while replacing every occurrence of the specified value - it then overrides the original file with the new file by performing a `move`. This caused the replace to work even when RStudio didn't have write permissions for that file. 
This PR tests if the original file can be written to before starting the replace process and immediately before performing the move. This will prevent the process from going forward with replace logic when it fails on the first check, and ensure the permissions were not changed by an outside process immediately before the `move`. 

This PR also fixes a, possibly impossible with the current UI, bug that was discovered while writing R unit tests where the `grep` command would have invalid syntax if a blank space was passed for the include or exclude tags.

### CODE REVIEW

File: src/cpp/session/modules/SessionFind.cpp [hunk 1]
```diff
@@ -470,6 +470,12 @@ class GrepOperation : public boost::enable_shared_from_this<GrepOperation>
       }
    }
 
+   Error testWritePermissions(const FilePath& filePath)
+   {
+      std::shared_ptr<std::ostream> testStream;
+      return filePath.openForWrite(testStream, /*in_truncate*/ false);
+   }
+
```
Comment (MariaSemple) [inline src/cpp/session/modules/SessionFind.cpp]: I'm not sure if there's a general use case for a test like this. If there is it would be good to have such a function in FilePath.hpp/cpp. What do you think @jmcphers?

Comment (melissa-barca) [reply src/cpp/session/modules/SessionFind.cpp]: @jmcphers There is a function in FileMode.hpp that does essentially the same thing `isFileWriteable` but doesn't work for Windows (in general, FileMode.hpp isn't supported on Windows). Where that function is called it looks like we don't do any type of check for Windows so it might make sense to add this somewhere more generic.

Comment (jmcphers) [reply src/cpp/session/modules/SessionFind.cpp]: There is a subtle distinction between "does this file have the write access bit set for me" and "can I actually write to this file". There is no way to validate the latter without actually opening a handle which can have some side effects (especially on NFS mounted volumes). I think it's fine to move this into FilePath itself but we might leave a comment about reading the access bits instead unless it's important to guarantee success.

Comment (melissa-barca) [reply src/cpp/session/modules/SessionFind.cpp]: I added this to FilePath, in the same commit I fixed a bug I discovered in testing this where we were losing the detailed error message in certain cases.

File: src/cpp/shared_core/include/shared_core/FilePath.hpp [hunk 2]
```diff
@@ -573,6 +573,14 @@ class FilePath
     */
    Error openForWrite(std::shared_ptr<std::ostream>& out_stream, bool in_truncate = true) const;
 
+   /*
```
Comment (MariaSemple) [inline src/cpp/shared_core/include/shared_core/FilePath.hpp]: Nit: methods in shared_core files are alphabetical. Could you move this just before the `private:` section? Also in the CPP file.

File: src/cpp/shared_core/include/shared_core/FilePath.hpp [hunk 3]
```diff
@@ -573,6 +573,14 @@ class FilePath
...
+    * @brief Checks if a file can be written to by opening the file
```
Comment (MariaSemple) [inline src/cpp/shared_core/include/shared_core/FilePath.hpp]: Nit: periods at the ends of the sentences and a blank comment line between the @brief and long descriptions.

Comment (melissa-barca) [reply src/cpp/shared_core/include/shared_core/FilePath.hpp]: Fixed 👍

File: src/cpp/shared_core/FilePath.cpp [hunk 4]
```diff
@@ -1295,6 +1289,12 @@ void FilePath::setLastWriteTime(std::time_t in_time) const
    }
 }
 
+Error FilePath::testWritePermissions() const
+{
+   std::shared_ptr<std::ostream> testStream;
+   return openForWrite(testStream, false);
```
Comment (MariaSemple) [inline src/cpp/shared_core/FilePath.cpp]: Do you know if this could create an empty file on disk if the file doesn't exist? I'm not sure.

File: src/cpp/shared_core/include/shared_core/FilePath.hpp (hunk 2 above)
Comment (melissa-barca) [reply src/cpp/shared_core/include/shared_core/FilePath.hpp]: Done

File: src/cpp/shared_core/FilePath.cpp (hunk 4 above)
Comment (jmcphers) [reply src/cpp/shared_core/FilePath.cpp]: Yes, it's very likely it will do this (good thought!)

Comment (melissa-barca) [reply src/cpp/shared_core/FilePath.cpp]: I updated the function so it no longer calls openForWrite, but borrows similar modified logic so that it only opens the file if it exists. I also updated the comment if FilePath.hpp to reflect this.

File: src/cpp/shared_core/FilePath.cpp [hunk 5]
```diff
@@ -1291,8 +1291,52 @@ void FilePath::setLastWriteTime(std::time_t in_time) const
...
+   }
+   catch(const std::exception& e)
+   {
+      Error error = systemError(boost::system::errc::io_error,
+                                ERROR_LOCATION);
+      error.addProperty("what", e.what());
+      error.addProperty("path", getAbsolutePath());
+      return error;
+   }
+
```
Comment (MariaSemple) [inline src/cpp/shared_core/FilePath.cpp]: Right now the ostream will be leaked if the function completes successfully. In openForWrite, the ownership is transferred to a smart pointer before the function exits. I think we should delete it before returning Success.

This also opens another question (which applies to the existing implementation of openForWrite) - is it possible for pResult to be initialized when an exception is thrown? In that case, the ostream would be leaked in that case as well. We could avoid this in both places by declaring the pResult outside of the try and deleting it in the catch if it's not null.

Comment (MariaSemple) [reply src/cpp/shared_core/FilePath.cpp]: Alternately in this implementation we can use a local ostream rather than a pointer, which would solve both problems.

Comment (melissa-barca) [reply src/cpp/shared_core/FilePath.cpp]: Thanks for pointing this out. I cleaned up the deletes and updated openForRead as well. Unfortunately because of this line https://github.com/rstudio/rstudio/blob/bugfix/replace-respect-permissions/src/cpp/shared_core/FilePath.cpp#L1317 I think it's cleaner to use a pointer here than a local variable. I did some testing on windows using a local variable and got some strange results.
