### PR TITLE
Dataviewer bugfixes, multisort

### LINKED ISSUE #1691: can' t sort on multiple columns in data viewer
I tried shift and click but it just select the column (the arrow turns blue) but no sorting occurs.
For example here I sorted by column "a" decreasing then wanted to sort by "c" column but nothing happens apart the arrow becoming blue

`View(data.frame(a = rep(1:4, each = 3), b = 1:3, c = 1:2))`

image

I use the Fedora build by the way on SLED Rstudio version 1.1.383

### LINKED ISSUE #3465: Column-names row includes in Data Viewer row count
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.2.956-2
    OS Version      : MacOS 10.14 Mojave & Ubuntu 16.04.5 w/ Chrome
    R Version       : 3.4.4 & 3.5.1

### Steps to reproduce the problem

1. `View(mtcars)`
2. Make Source pane short enough so that only a few rows are displayed in the Data Viewer
3. Scroll all the way to the bottom of the Data Viewer
4. Shrink window so it only has enough room to show one row
5. Scroll all the way to the bottom so that no rows are shown

### Describe the problem in detail

The row count includes the column-names row in the count, so the indicator at the bottom of how many rows are displayed adds one extra.

1–5 instead of 1–4:
view_mtcars_top

30–32 instead of 31–32:
view_mtcars_bottom

33 instead of none:
view_mtcars_empty

All three misbehaviors occur in Desktop. I can only reproduce the first in Server. 
### Describe the behavior you expected

The column-names row should not be included in the Data Viewer's row count.

### LINKED ISSUE #3888: attempting to shrink a data viewer column can also trigger a sort
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1119
    OS Version      : macOS 10.14.1
    R Version       : 3.5.1

### Steps to reproduce the problem

Open the data viewer with e.g.

``` r
View(mtcars)
```

Then, try to 'shrink' a column, e.g. the `qsec` column. Click the resizer on the right side of the header cell, move the mouse to the left, and then release.

### Describe the problem in detail

The view is then sorted by the associated cell.

scroll

### Describe the behavior you expected

Resize operations shouldn't also trigger a sort.

### LINKED ISSUE #4517: Data viewer status bar progressively becomes out of sync with visible data
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1327
    OS Version      : Windows 10 x64 1803 build 17134.648
    R Version       : 3.5.1

### Steps to reproduce the problem
View a data frame with more rows than can fit on one screen.
`View(airquality)`

### Describe the problem in detail

The data viewer appears to calculate the visible portion of the data set incorrectly. Here, rows 1-22 are visible, but the status bar indicates that rows 1-24 are being shown (perhaps it is including the height of the header row when calculating what should be visible). This discrepancy compounds as you scroll further down the dataset; by the time one scrolls to the end of the data set, the status bar says that rows 144-153 are being shown, when it is in fact rows 133-153.

For longer data sets (~200+ rows), this can result in situations where there is no overlap between what is shown and what the status bar says is shown.

Minor observation: rows with NA cells are taller than those without any NA values.  

### Describe the behavior you expected
The status bar should show the actual rows visible above it.

### PR DESCRIPTION
**Pull request by adamconroy**
Commit 5d4b8db and 4264064
Fixes #4517 
Fixes #3465 

Commit ff3e2f8
Fixes #3888 

Commit faec964
Fixes #1691

### CODE REVIEW

**Comment by adamconroy** [comment]
One minute, need to add a polyfill for `Element.closest` because of course IE11 doesn't support it...

**Comment by gtritchie** [comment]
> One minute, need to add a polyfill for `Element.closest` because of course IE11 doesn't support it...

At some point should we add a build step that consolidates our increasing number of polyfills into a single script to reduce downloads when starting up?

**Comment by adamconroy** [comment]
We should definitely add a generic polyfill step like babel core eventually. Unfortunately our setup is so funky (this polyfill for the dataviewer wouldn't be encapsulated in a normal build step because it's iframed in) that making it generic and consistent without a big overhaul will be tricky.

File: src/cpp/session/resources/grid/datatables/js/jquery.dataTables.js [hunk 1]
```diff
@@ -1636,7 +1636,7 @@
     if ( row.nTr === null )
     {
       nTr = nTrIn || document.createElement('tr');
-      nTr.setAttribute("data-row", iRow);
+      nTr.setAttribute("data-row", iRow + oSettings._iDisplayStart);
```
Comment (adamconroy) [inline src/cpp/session/resources/grid/datatables/js/jquery.dataTables.js:1639]: Found that if you made the window small enough such that it was AJAXing data in constantly the row number would be off here as `iRow` doesn't encapsulate the data pagination.

**Comment by adamconroy** [comment]
Found a couple small bugs in the code that I fixed and added the polyfill. This is now ready for review.

File: src/cpp/session/modules/SessionDataViewer.R [hunk 2]
```diff
@@ -414,22 +414,28 @@
...
     {
-      # extract the first value from each cell for ordering (handle
-      # vector-valued columns gracefully)
-      x <- as.data.frame(x[order(vapply(x[[col]], `[`, 0, 1), 
-                                 decreasing = identical(dir, "desc")), ,
-                           drop = FALSE])
+      idx <- cols[[i]]
+      if (length(x[[idx]]) > 0)
+      {
+        if (dirs[[i]] == "asc")
```
Comment (jmcphers) [inline src/cpp/session/modules/SessionDataViewer.R:425]: Because of R's wonky comparison semantics, use `identical(x, y)` to compare strings instead of `==` (for pretty much the same reasons `===` is generally preferred over `==` in JS)

File: src/cpp/session/modules/data/DataViewer.cpp [hunk 3]
```diff
@@ -483,15 +483,33 @@ json::Value getData(SEXP dataSEXP, const http::Fields& fields)
...
+   std::vector<std::string> orderdirs;
+   int orderIdx = 0;
+   int ordercol = -1;
+   std::string orderdir;
+   do
+   {
+      std::string ordercolstr = "order[" + std::to_string(orderIdx) + "][column]";
+      std::string orderdirstr = "order[" + std::to_string(orderIdx) + "][dir]";
+      ordercol = http::util::fieldValue<int>(fields, ordercolstr,  -1);
+      orderdir = http::util::fieldValue<std::string>(fields,  orderdirstr, "asc");
```
Comment (jmcphers) [inline src/cpp/session/modules/data/DataViewer.cpp:502]:
```suggestion
      orderdir = http::util::fieldValue<std::string>(fields, orderdirstr, "asc");
```

File: src/cpp/session/modules/SessionDataViewer.R (hunk 2 above)
Comment (jmcphers) [reply src/cpp/session/modules/SessionDataViewer.R:425]: The most famous example:

```
> x <- NULL
> y <- "foo"
> if (x == y) message("Equality achieved")
Error in if (x == y) message("Equality achieved") : 
  argument is of length zero
```
