### PR TITLE
Forward scrolling from chunk callback to editor

### LINKED ISSUE #2202: Table made from kable in R Markdown interferes with scrolling using mouse or trackpad
### System details

    RStudio Edition : Server and Desktop
    RStudio Version : 1.1.383, 1.1.423, 1.2.342
    OS Version      : MacOS Desktop and Ubuntu
    R Version       : 3.4.3

### Steps to reproduce the problem
1. Create an R Markdown document that contains the sample code below. The full Rmd file is here (rename from .txt to .Rmd): [kable_scolling.txt](https://github.com/rstudio/rstudio/files/1727946/kable_scolling.txt)
``kable(matrix(1:100), col.names = "Long")``
``kable(matrix(1:1), col.names = "Short")``

2. Run —> Run All
3. Click inside the “kable_long” chunk
4. Scroll down past the output using the trackpad (two fingers) or mouse (third button/wheel).
5. Try to scroll up or down.
6. Click inside  the “kable_short” chunk
7. Scroll down past the output using the trackpad or mouse.
8. Try to scroll up or down

kable_scrolling

### Describe the problem in detail

Outputted R Markdown chunks containing kable() tables interfere with scrolling using the Mac trackpad’s two-finger scroll gesture or mouse wheel/third button. If the cursor starts off in code, and then you try to scroll up or down past an output with a table generated using kable(), then the cursor automatically jumps into the output and the screen stops scrolling. Then one of two things happen:
1. If there are more rows in the table than can be displayed at once, the mouse now scrolls up and down within it. This is normal behavior, if one had clicked on the output, but not in this case, because we tried to scroll past the output.
2. If the output layout is large enough that all the records are displayed, the screen simply pauses. It’s as if the mouse jumped into the output table, but there’s nothing to scroll through, so it just sits there.

The behavior is consistent on Server. On Desktop, it's a bit inconsistent. Sometimes, when (1) occurs, if you scroll all the way down to the final row or up to the first row, the mouse jumps back out and the screen continues to scroll. Also, (2) doesn’t always happen.

### Describe the behavior you expected

The scrolling will continue past the outputs. Scrolling within the outputted table will only happen in case (1)—more rows than can be displayed at once—with a mouse click on it. In case (2)—all rows are displayed—not only should the scrolling continue past the output, there should be no equivalent to clicking within the output; scrolling should continue past it.

### LINKED ISSUE #8008: Unable to scroll in source pane after chunk grading
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.915
    OS Version      : MacOS
    R Version       : 4.0.2

### Steps to reproduce the problem
1. register a callback
remotes::install_github("rstudio/rstudioapi")
rstudioapi::registerChunkCallback(mycallback)

```
mycallback <- function(chunkName, chunkCode) {
  template <- "<div id=\"abc123\">\n  <div class=\"callbackActions\">\n\n  </div>\n  <div class=\"callbackResult\">\n\n  </div>\n</div>\n\n<style>\n.callbackSuccess {\n  background-color: #ACA;\n}\n\n.callbackFailure {\n  background-color: #CAA;\n}\n</style>\n<script>\n  function handle(name, chunkCode, result){\n\n    var divID = \"abc123\"; // A random value generated in the R callback\n    var el = document.querySelectorAll('#' + divID)[0];\n    var resultsEl = el.querySelectorAll('.callbackResult')[0];\n    var actionsEl = el.querySelectorAll('.callbackActions')[0];\n\n    window.doGrade = function(url){\n      var request = new XMLHttpRequest();\n      request.open('POST', url, true); // Simulate a happy response\n      // request.open('GET', 'http://httpbin.org/post', true); // Simulate a bad response\n      // request.open('GET', 'http://yoidontevenexisthere.org/post', true); // Simulate an invalid request\n      request.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded; charset=UTF-8');\n  \n      request.onload = function() {\n        if (this.status >= 200 && this.status < 400) {\n          // Success!\n          var resp = this.response;\n          resultsEl.innerHTML = '<h3>Noice!</h3><p><pre>' + \n            'I ran the chunk `' + name + '` with the following code:\\n\\n```\\n' +\n            chunkCode + '\\n```\\n\\n and it all worked great!' +\n            '</pre></p><p><img src=\"https://www.unilad.co.uk/wp-content/uploads/2018/07/success-kid-original.jpg\" width=\"500px\" height=\"330px\"/></p>';\n          resultsEl.classList.add('callbackSuccess');\n          resultsEl.classList.remove('callbackFailure');\n        } else {\n        console.log(\"Setting\");\n        console.log(resultsEl);\n          // We reached our target server, but it returned an error\n          resultsEl.innerHTML = '<h3>Bad response</h3><p><pre>' + this.status + ' HTTP status</pre></p><p><img src=\"https://sayingimages.com/wp-content/uploads/so-sad-cat-meme.jpg\" /></p>';\n          resultsEl.classList.add('callbackFailure');\n          resultsEl.classList.remove('callbackSuccess');\n        }\n      };\n  \n      request.onerror = function() {\n        resultsEl.innerHTML = '<h3>I can\\'t even..</h3><p><img src=\"https://i.ytimg.com/vi/GTJQ3JsaHcA/hqdefault.jpg\" /></p>';\n        // There was a connection error of some sort\n        resultsEl.classList.add('callbackFailure');\n        resultsEl.classList.remove('callbackSuccess');\n      };\n\n      request.send('user=person&pwd=password&organization=place&requiredkey=key');\n    }\n      \n    actionsEl.innerHTML = '';\n    resultsEl.innerHTML = '';\n\n    if (name === 'nobuttons') {\n      // Don't add anything\n    } else { \n      actionsEl.innerHTML = '<button onclick=\"doGrade(\\'http://httpbin.org/post\\')\">Success</button>' +\n        '<button onclick=\"doGrade(\\'http://httpbin.org/get\\')\">Failure</button>' + \n        '<button onclick=\"doGrade(\\'http://thiserverdoesntevenexisthereyo.co.uk\\')\">Wat</button>';\n    }\n  }\n  handle(\"chunkName\", \"my code here\", {});\n</script>"
  rand <- round(runif(1, 1e8, 1e9))
  htmlres <- gsub("chunkName", chunkName, template)
  htmlres <- gsub("my code here", chunkCode, htmlres)
  return(list(html = htmlres))
}
```

2. Run a chunk in R notebook
3. Try to scroll in the source pane

### Describe the problem in detail
The user cannot scroll in the source pane after running the chunk. They have to move the mouse cursor to the scrollbar to scroll.
### Describe the behavior you expected
User should be able to scroll in the source pane

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### PR DESCRIPTION
**Pull request by melissa-barca**
### Intent

Fixes #8008 

Prior to this fix scrolling over chunk callback output would do nothing and interrupt scrolling occuring on the editor. Now the iframe will forward `mousewheel` or `wheel` events to the editor so it can handle the scrolling.

### Approach

Since the iframe was not triggering the scroll event, the iframe forwards wheel events to the editor -- ace editor was coded to trigger scroll events from these. Due to browsers handling the wheel events differently, we need to check which event is supported to set the listener. I ran into an issue with Chrome where if listeners were set for `wheel` or `wheel` and `mousewheel` the scroll wasn't triggered so `mousewheel` is used as the preferred event.

A similar approach can be used to fix #2202 but since that would require some additional logic I didn't implement it with this PR. 

I also included a fix to set the height of the output to 0 whenever the output is mutated. Without this the frame was not resized if its content shrunk.

### QA Notes

We need to make sure this is working for all supported browsers.

### CODE REVIEW

File: src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java [hunk 1]
```diff
@@ -447,15 +451,29 @@ public void showCallbackHtml(String htmlOutput)
...
+               new Timer()
+               {
+                  @Override
+                  public void run()
+                  {
+                     int newHeight = frame.getWindow().getDocument().getDocumentElement().getOffsetHeight();
+                     frame.getElement().getStyle().setHeight(newHeight, Unit.PX);
+                     onHeightChanged();
+                  }
+               }.schedule(50);
```
Comment (jmcphers) [inline src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java:476]: This could very well be happening over a WAN or slow connection so 50ms may not be enough time for everything to load (such that we are guaranteed to have the final height). Maybe we should wait for the frame's `load` event?

**Comment by kevinushey** [comment]
We had previously done and backed out something very similar:

https://github.com/rstudio/rstudio/pull/2533

primarily because the experience with dual scrollbars is unpleasant. Does this PR run into the same sorts of issues?

**Comment by melissa-barca** [comment]
> We had previously done and backed out something very similar:
> 
> #2533
> 
> primarily because the experience with dual scrollbars is unpleasant. Does this PR run into the same sorts of issues?

The html callback output is slightly different from the standard html chunk output so I don't think this will cause the same issues. The iframes will not have scrolling as the size adjusts dynamically and gets cut off if it exceeds the max height with the overflow hidden.
https://github.com/rstudio/rstudio/blob/master/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputWidget.java#L344-L349

File: src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java (hunk 1 above)
Comment (melissa-barca) [reply src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java:476]: Unfortunately the `load` event gets sent only to the iframe and isn't forwarded to the IDE. We have a `MutationObserver` monitoring the iframe for changes to know when to adjust the height, but the callback I've been using downloads images via HTTP requests so the observer recognizes that change and immediately adjusts the height, but before the image has downloaded. 
I talked with Jeff about this and it shouldn't be a major issue as the majority of the images they'll be sending will be small. We also discovered that if the `` tag in the callback is passed with a `height` argument then we can circumvent the need to delay the load. I still like the idea of delaying it slightly if it's not noticeable. What do you think?

Comment (kevinushey) [reply src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java:472]: Do we have any other way of detecting that the frame is fully loaded? I wonder if this should be a repeating command that basically polls until the iframe is "ready", and then runs only when ready.

**Comment by kevinushey** [comment]
> The html callback output is slightly different from the standard html chunk output so I don't think this will cause the same issues. The iframes will not have scrolling as the size adjusts dynamically and gets cut off if it exceeds the max height with the overflow hidden.

Ah, got it! That sounds good to me.

File: src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java (hunk 1 above)
Comment (melissa-barca) [reply src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java:472]: Unfortunately not that I'm aware of without requiring the user to include some logic in the callback (and having them set the img height is probably the simplest way); both `load` and `readystate` give false positives.

**Review by kevinushey — APPROVED** [review]
LGTM!

**Review by jmcphers — APPROVED** [review]
