### PR TITLE
work around Mojave bug with invisible inputs in addins

### LINKED ISSUE #3602: addin UI elements not visible
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.1026
    OS Version      : macOS 10.14
    R Version       : 3.5.1

### Steps to reproduce the problem

Try running an addin, e.g. the reprex addin.

### Describe the problem in detail

UI elements are invisible:

screen shot 2018-10-05 at 8 58 25 am

### Describe the behavior you expected

UI elements should render without issue.

### PR DESCRIPTION
**Pull request by kevinushey**
Closes #3602.

Note that while I would've preferred to do this entirely in the front-end, cross-site origin rules disallow us from modifying the Shiny gadget window (as its running on a different port, and so a different origin).

### CODE REVIEW

File: src/cpp/session/modules/SessionRAddins.R [hunk 1]
```diff
@@ -14,3 +14,36 @@
...
+   rm(".rs.addins.savedShinyResponseFilter", envir = .rs.toolsEnv())
+   
+   # ensure text is character rather than raw (not sure if this can happen
+   # but other shiny.http.response.filters do this so best to be safe)
+   if (is.raw(response$content))
+      response$content <- rawToChar(response$content)
+   
+   # inject our CSS into the response
+   css <- '<style type="text/css">select, input { zoom: 1.000001; }</style>'
+   response$content <- sub('<head>', paste('<head>', css, sep = ""), response$content, fixed = TRUE)
```
Comment (jmcphers) [inline src/cpp/session/modules/SessionRAddins.R]: Is `head` always going to be lower case?

File: src/gwt/src/org/rstudio/studio/client/workbench/addins/Addins.java [hunk 2]
```diff
@@ -143,10 +146,31 @@ public void execute()
...
-                                                              false));
+                     
+                     if (BrowseCap.isMacintoshDesktopMojave())
+                     {
+                        server_.prepareForAddin(new ServerRequestCallback<Void>()
+                        {
+                           @Override
+                           public void onResponseReceived(Void response)
+                           {
+                              SendToConsoleEvent event = new SendToConsoleEvent(code, true, false, false);
```
Comment (jmcphers) [inline src/gwt/src/org/rstudio/studio/client/workbench/addins/Addins.java]: If an error occurs in the add-in such that the Shiny response never happens, then our response filter will be left dangling. I can't think offhand whether there's a good way to prevent this, though -- what do you think?

File: src/cpp/session/modules/SessionRAddins.R [hunk 3]
```diff
@@ -14,3 +14,36 @@
...
+})
+
+.rs.addFunction("addins.shinyResponseFilter", function(request, response)
+{
+   # bail if this isn't the root response
+   if (!identical(request$PATH_INFO, "/"))
+      return(response)
+   
+   # remove our old handler
+   options(shiny.http.response.filter = .rs.addins.savedShinyResponseFilter)
```
Comment (jmcphers) [inline src/cpp/session/modules/SessionRAddins.R]: This implies we'll only filter the very first request for `/`. Is it possible for `/` to be requested more than once? (e.g. can the app trigger a reload of the frame?)

**Comment by jmcphers** [comment]
I'm assuming that this doesn't happen in 1.1 patch since this rendering issue is specific to the combination of Mojave and Chromium -- is that right?

**Comment by kevinushey** [comment]
That's right, this only occurs on macOS with v1.2 as it's a Chromium / Mojave interaction.

File: src/cpp/session/modules/SessionRAddins.R (hunk 1 above)
Comment (kevinushey) [reply src/cpp/session/modules/SessionRAddins.R]: I'm not sure -- for that reason I should probably use `ignore.case = TRUE` here.

File: src/gwt/src/org/rstudio/studio/client/workbench/addins/Addins.java (hunk 2 above)
Comment (kevinushey) [reply src/gwt/src/org/rstudio/studio/client/workbench/addins/Addins.java]: One possibility would be for us to clear the filter on the next ConsolePromptEvent or something similar -- that might be more robust overall (and would allow us to properly handle the case where an addin might attempt a reload, however rare that might be)

File: src/cpp/session/modules/SessionRAddins.R (hunk 3 above)
Comment (kevinushey) [reply src/cpp/session/modules/SessionRAddins.R]: I think it's possible, but I'm not aware of any addins that do this. That said, re: previous comment if we instead clear the handler with some other signal that the associated addin has stopped running we would be clear (e.g. ConsolePromptEvent)

**Comment by kevinushey** [comment]
I think this is ready for re-review -- @jmcphers let me know what you think.
