### PR TITLE
Always refresh data viewer when source data changes

### LINKED ISSUE #1819: Data viewer's tooltips are not reliable
In the data viewer, when hovering on a column header, a tooltip is displayed, containing info such as `column 4: numeric with range 0.1 - 2.5`. However the content is sometimes unaccurate or wrong.

A few examples:

```r
df <- data.frame(v = 1:2)
View(df) # wait for the tab to display and don't close it
df$v <- c("a", "b")
```
--> In the data viewer the column's content is updated but the tooltip does not change.

```r
df2 <- data.frame(1:2, Sys.time(), Sys.Date())
View(df2)
```
--> The tooltips report that column 1 is numeric, and columns 2 & 3 are of "unknown" type. That's not wrong but it would be nice to have "integer", "POSIXct" and "Date" instead (i.e. as in the output of `str(df2)`).

```r
View(head(iris, 1))
```
--> Strangely the numeric columns are marked as "unknown".

RStudio 1.1.383

<details><summary>Session info</summary>

``` 
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3    yaml_2.1.15   
```

</details>

### PR DESCRIPTION
**Pull request by adamconroy**
Fixes #1819
(and possibly some other filed issues)

Currently we are just reloading the data and trying to keep the visible state as much intact as possible when the underlying data changes. Unfortunately this leaves the Dataviewer in a very weird state. Things like tooltips, paging, filters can all get out of sorts and can get very confused when the "fire and forget" HTML gets partially out of sync with the data. With the way that it's currently set up (no id's on headers, no objects tied to the HTML directly) we can't just put new data into the rows without a full refresh. I tried to fix just the issue filed in the bug but I found quite a few other things wrong with this. If this feature is worth the bugs it causes I think its worth an enhancement discussion.

I'm considering options for medium sized changes that we can do in 1.4 to get us closer to a real client-side data+view synced model but at the moment there is too much complexity with too little control for this in-situ reload to work.

Also, I ran Prettier against `dtviewer.js` in the first commit with no config, all defaults to remove any personal subjectivity.

### CODE REVIEW

File: src/cpp/session/resources/grid/dtviewer.js [hunk 1]
```diff
@@ -1543,23 +1543,7 @@
     // restore any scroll handlers (this can get called on tab activate)
     restoreScrollHandlers();
 
-    if (structureChanged) {
```
Comment (jmcphers) [inline src/cpp/session/resources/grid/dtviewer.js]: We should also remove all the plumbing that decides if the structure changed.

**Comment by jmcphers** [comment]
LGTM, don't forget to add a NEWS entry!
