### PR TITLE
explicitly ignore '.git' folder on Windows

### LINKED ISSUE #2141: IDE hangs when opening certain Git-managed projects on Windows
A number of users have reported issues with RStudio hanging on open with Windows. The general symptoms are:

1. The IDE surface loads and initially appears to be responsive;
2. However, attempting to execute any R code fails (the console never prints any output),
3. Any other actions in the IDE silently appear to do nothing,
4. Attempts to close the IDE also fail.

@andrie experienced this with one of his projects, and discovered that it seemed to be linked to the usage of Git -- the hang goes away once the `.git` folder is deleted.

Opening RStudio with Project Explorer, it seems as though RStudio is stuck in a loop querying the project with `git status`, while the asynchronous package completer tries to run as well. Note that the asynchronous package completer never finishes running, but `git` instances keep getting repeatedly launched.

screen shot 2018-02-05 at 4 31 54 pm

The error logs have this:

```
06 Feb 2018 00:32:37 [rsession-kevin] ERROR system error 5 (Access is denied) [path=C:/Users/kevin/Desktop/checkpoint/.git/index.lock]; OCCURRED AT: unsigned __int64 __cdecl rstudio::core::FilePath::size(void) const C:\jenkins\workspace\IDE\windows\src\cpp\core\FilePath.cpp:375; LOGGED FROM: unsigned __int64 __cdecl rstudio::core::FilePath::size(void) const C:\jenkins\workspace\IDE\windows\src\cpp\core\FilePath.cpp:375
06 Feb 2018 00:34:42 [rsession-kevin] ERROR system error 2 (The system cannot find the file specified) [path=C:/Users/kevin/Desktop/checkpoint/.git/index.lock]; OCCURRED AT: unsigned __int64 __cdecl rstudio::core::FilePath::size(void) const C:\jenkins\workspace\IDE\windows\src\cpp\core\FilePath.cpp:375; LOGGED FROM: unsigned __int64 __cdecl rstudio::core::FilePath::size(void) const C:\jenkins\workspace\IDE\windows\src\cpp\core\FilePath.cpp:375
```

Attempting to manually execute `git status` does succeed when launched from the command line, so it's not immediately obvious what the issue might be (unless it's the collision between these child processes that is somehow the culprit).

### PR DESCRIPTION
**Pull request by kevinushey**
This PR seeks to resolve an issue where attempts to launch the IDE could fail if the `.git` folder was not marked as hidden. Effectively, the IDE would get deadlocked between the file monitor scanning for changes to the `.git/index.lock` file, and attempts to call `git status` to populate the Git pane.

Resolves #2141.

@jjallaire, let me know if this feels like the right change or if there's a more appropriate place for this fix to live.

Do we want to be resilient against other hidden folders that may become unhidden (e.g. the `.Rproj.user` folder)?

### CODE REVIEW

File: src/cpp/core/system/file_monitor/Win32FileMonitor.cpp [hunk 1]
```diff
@@ -488,6 +489,20 @@ Error readDirectoryChanges(FileEventContext* pContext)
    }
 }
 
+bool gitFilter(const FileInfo& fileInfo,
+               const boost::function<bool(const FileInfo&)>& filter)
+{
+   // screen out '.git' folder
+   if (fileInfo.isDirectory() &&
+       boost::algorithm::ends_with(fileInfo.absolutePath(), ".git"))
```
Comment (jmcphers) [inline src/cpp/core/system/file_monitor/Win32FileMonitor.cpp]: Nit: this will screen out `foo.git` and `bar.git` as well.
