### PR TITLE
Fix chunk highlighting issue

### LINKED ISSUE #8088: Switching visual mode on/off with third pane column leads to misaligned highlighting of chunks
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.869
    OS Version      :  macOS Catalina 10.15.6
    R Version       : 4.0.3 (2020-10-10)

### Steps to reproduce the problem

1. Open RStudio
2. Open new Rmarkdown file
3. Add third source column
4. Switch to visual mode
5. Modify one chunk (e.g. add more lines)
6. Switch back to code-mode

### Describe the problem in detail

The chunk modified in step 5) is not highlighted correctly, instead the highlighting still applies to 
the code lines from before modifying.

### Describe the behavior you expected

Adapted the highlighting of the chunk when third source column is active 

Thanks for all your great work! the option for additional columns is great!

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

Screenshot 2020-10-16 at 14 35 55

### PR DESCRIPTION
**Pull request by melissa-barca**
### Intent

Fixes #8088 

When a document was created before a new source column and later had its mode changed, the highlighted background indicating a chunk was properly aligned with the chunk. 

### Approach

Layout changes for additional columns require existing source columns to detach and re-attach. Prior to this fix, the highlighter's event handlers were removed when detached but never added back since this wasn't necessary prior to 1.4. 

### QA Notes

See original ticket.

### CODE REVIEW

File: src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceBackgroundHighlighter.java [hunk 1]
```diff
@@ -277,6 +277,18 @@ public void onAttachOrDetach(AttachEvent event)
             documentChangedHandler_ = null;
          }
       }
+      else
+      {
+         handlers_ = new HandlerRegistrations(
```
Comment (kevinushey) [inline src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceBackgroundHighlighter.java:282]: Should we also remove any existing handlers here as well, just in case? (Since we do initialize handlers in the constructor here: https://github.com/rstudio/rstudio/blob/e2be2eea8c7bf0852bac78034dbddfa5d71be245/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceBackgroundHighlighter.java#L168-L170)

Or, maybe we can just remove that initialization and only init in attach / detach as you currently have things?

Comment (melissa-barca) [reply src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceBackgroundHighlighter.java:282]: We can't remove the constructor's initialization because otherwise this function won't be set as the editors' attach handler and doesn't get called. I updated the code to remove handlers regardless of attaching or detaching.

**Review by kevinushey — APPROVED** [review]
LGTM!
