### PR TITLE
re-encoding of Help pane URIs no longer necessary

### LINKED ISSUE #4829: No help found for topic graphical%20parameters in any package.
### System details

    RStudio Edition: Desktop
    RStudio Version: 1.2.1335 and 1.2.1522
    OS Version: Windows 10 and Kubuntu 18.04.2
    R Version: 3.6.0

### Steps to reproduce the problem
1. Open the help for "box" (from the graphics package) in the help pane.
2. In the "Arguments" section click on the link to "graphical parameters".

alternative:
1. Open the help for "InternalMethods" in the help pane.
2. Click on the link to "group generic".

### Describe the problem in detail
An error is displayed:
`No help found for topic graphical%20parameters in any package.`

or with the alternative:
`No help found for topic group%20generic in any package.`

### Describe the behavior you expected
The links should work. Other links work fine so this may have something to do with the withespace in the middle?

### PR DESCRIPTION
**Pull request by kevinushey**
Fixes #4829.

I'm guessing that the update to Chromium changed the way URIs are passed around on Linux / macOS Desktop; now, they're always encoded and so we do not need to attempt to re-encode the URI.

(As an aside, I believe the bug arose because we weren't successfully detecting that the URI component "graphical%20parameters.html" was already HTML encoded)

### CODE REVIEW

File: src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java [hunk 1]
```diff
@@ -187,19 +187,7 @@ function addEventHandler(subject, eventName, handler) {
             thiz.@org.rstudio.studio.client.workbench.views.help.HelpPane::unload()();
          });
       } ;
-      $wnd.helpNavigate = function(url, encode) {
-         // on some platforms url may arrive unencoded; on others it will already be encoded. to
-         // ascertain the difference, check to see if the url contains any characters that require
-         // encoding. 
-         if (encode)
-         {
-            var re = new RegExp("^([!#$&-;=?-[]_a-z~]|%[0-9a-fA-F]{2})+$");
```
Comment (jmcphers) [inline src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java]: Very happy to see this ugly regex go away!
