### PR TITLE
Omit "Presentation" from labels

### LINKED ISSUE #10213: Redundant wording in Pane Layout options
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.01.0-daily+290 "Prairie Trillium" Daily (5584871710f8df9db57af3e0bb31cf85f8f6d7f5, 2021-12-07) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 12_0_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
    OS Version      : macOS 12.0.1
    R Version       : 4.1.2

### Steps to reproduce the problem

- Go to RStudio > Preference > Pane layout
- Click on the name of the pane starting with Environment to expand the description

### Describe the problem in detail

It says "Presentations, Presentation", which is redundant

pane-layout

### Describe the behavior you expected

It should say just "Presentation"

- [ x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### PR DESCRIPTION
**Pull request by romainfrancois**
### Intent

addresses #10213

### Approach

I've tried to be minimal, as the "Presentation" item seems te be special somehow. The associated checkbox seems to be always hidden, in the `ModuleList` constructor: 

```java
ModuleList(String width)
      {
         checkBoxes_ = new ArrayList<>();
         FlowPanel flowPanel = new FlowPanel();
         for (String module : PaneConfig.getAllTabs())
         {
            CheckBox checkBox = new CheckBox(module, false);
            checkBox.addValueChangeHandler(this);
            checkBoxes_.add(checkBox);
            flowPanel.add(checkBox);
            if (module == "Presentation")
              checkBox.setVisible(false);
         }

         ScrollPanel scrollPanel = new ScrollPanelWithClick();
         scrollPanel.setStyleName(res_.styles().paneLayoutTable());
         scrollPanel.setWidth(width);
         scrollPanel.add(flowPanel);
         initWidget(scrollPanel);
      }
```

But still there however, this pr just skips it from `getValue()` so that it does not appear in e.g. 

```java
String itemText1 = tabSet1ModuleList_.getValue().isEmpty() ?
         "TabSet" : StringUtil.join(tabSet1ModuleList_.getValue(), ", "); 
```

image
image

### Automated Tests

Supposedly we could add a unit test checking that `ModuleList.getValue()` does not include "Presentation" but I have yet to learn how to do that ... 

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

### CODE REVIEW

File: src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PaneLayoutPreferencesPane.java [hunk 1]
```diff
@@ -149,7 +149,7 @@ public void setSelectedIndices(ArrayList<Boolean> selected)
          ArrayList<String> value = new ArrayList<>();
          for (CheckBox checkBox : checkBoxes_)
          {
-            if (checkBox.getValue())
+            if (checkBox.getValue() && checkBox.getText() != "Presentation")
```
Comment (kevinushey) [inline src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PaneLayoutPreferencesPane.java:152]: Nit: in Java, comparison of strings with `==` and `!=` compares whether references are equal, so using `String.equals()` (or our `StringUtil.equals()`) is usually preferable.

In practice, because the code is compiled to JavaScript this will probably do the right thing, but IMHO it's best to "obey" the Java semantics here.

**Review by kevinushey — APPROVED** [review]

File: src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PaneLayoutPreferencesPane.java (hunk 1 above)
Comment (romainfrancois) [reply src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PaneLayoutPreferencesPane.java]: Thanks.

**Comment by romainfrancois** [comment]
This feels trivial, should I move #10213 to PT @mikebessuille ?

**Comment by mikebessuille** [comment]
@romainfrancois  Yep! absolutely

**Review by kevinushey — APPROVED** [review]
LGTM!
