### PR TITLE
Fixes for attempting to publish unrendered Rmd as final document

### LINKED ISSUE #3752: "rendered" publishing without rendering has UI issues
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1074
    OS Version      : macOS 10.14
    R Version       : 3.5.1

### Steps to reproduce the problem

1. Create a directory. Let's call it "static".
2. Create a simple Rmd in that directory. Even just a title in the YAML plus one paragraph is sufficient.
3. Click the publish button in the editor pane.
4. Choose to publish the rendered document (NOT the source).

### Describe the problem in detail

An error message is displayed noting that "Only rendered documents can be published to RStudio Connect.". This statement is incorrect, as both source and rendered documents can be deploy to Connect. Instead, we should say something like, "You chose to publish a rendered document to RStudio Connect but a rendering is not available."

The second issue is with the publishing window. Given the error message, we should not be showing the window. It is left in an unfortunate state, with both "Publish From" and "Publish To" appearing, the "Publish To" input being squat and empty, and the "Title" being blank (not inherited from the directory name, as is expected).

image

### Describe the behavior you expected

Given the expectation of a rendering, I expected a clear error explaining why I cannot publish my content and no publishing window.

### PR DESCRIPTION
**Pull request by gtritchie**
Timing issues when trying to dismiss publish wizard in scenarios described in #3752.

In one case the wizard dialog is shown in an incomplete state while an error message is displayed to user, then goes away when the error message is dismissed. In the other case, the dialog fails to dismiss via `indicator.onCompleted()`.

Fixed by using nested timers; not very satisfying, but fixes both cases in my testing on on desktop and server.

Secondary wording fix; change "Publish Source Code" in this dialog (which doesn't match the intent of the dialog) to "Publish to RStudio Connect".

BEFORE:

AFTER:

Fixes #3752

### CODE REVIEW

File: src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.java [hunk 1]
```diff
@@ -830,12 +831,41 @@ private void populateDeploymentFiles(final ProgressIndicator indicator)
...
+                     {
+                        RStudioGinjector.INSTANCE.getGlobalDisplay().showMessage(
+                              GlobalDisplay.MSG_INFO,
+                              "Finished Document Not Found",
+                              "To publish finished document to RStudio Connect, you must first render " +
+                                    "it. Dismiss this message, click Knit to render the document, " +
+                                    "then try publishing again.");
+                     }
+                  };
+                  showMessageTimer.schedule(100);
```
Comment (jmcphers) [inline src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.java]: Would deferring these to the next event loop work? (i.e. `Scheduler.ScheduleDeferred`)

Comment (gtritchie) [reply src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.java]: I tried that before I switched to a timer for the initial case(i.e. the inner timer) and it did not help.

I didn't try it on the second case (that prompted the second timer). I'll try that and see if I can eliminate one of the timers at least.
