### PR TITLE
Fix various columnOffset related DataViewer bugs

### LINKED ISSUE #4682: Wrong sorting in data viewer if columns in view don't start from the first
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1502
    OS Version      : macOS 10.14.4 (18E226)
    R Version       : 3.5.2 (2018-12-20)

### Steps to reproduce the problem

1. Read a dataframe with more than 50 columns.
2. Visualise a range of columns that does not include the first colum.
2. Sort in the data viewer any numeric column.

### Describe the problem in detail

When trying to sort a column in the data viewer, and the columns in view do not start with the first column, the sorting is wrong.

example

### Describe the behavior you expected

The expected behaviour should be correct sorting of the numeric values in the columns.

```
─ Session info ───────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.5.2 (2018-12-20)
 os       macOS Mojave 10.14.4        
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_GB.UTF-8                 
 ctype    en_GB.UTF-8                 
 tz       Europe/Rome                 
 date     2019-04-22                  

─ Packages ───────────────────────────────────────────────────────────
 package           * version    date       lib source        
 assertthat          0.2.1      2019-03-21 [1] CRAN (R 3.5.2)
 backports           1.1.4      2019-04-10 [1] CRAN (R 3.5.2)
 callr               3.2.0      2019-03-15 [1] CRAN (R 3.5.2)
 cli                 1.1.0      2019-03-19 [1] CRAN (R 3.5.2)
 coretta2018itapol * 0.0.0.9000 2019-04-14 [1] local         
 crayon              1.3.4      2017-09-16 [1] CRAN (R 3.5.0)
 desc                1.2.0      2018-05-01 [1] CRAN (R 3.5.0)
 devtools            2.0.2      2019-04-08 [1] CRAN (R 3.5.2)
 digest              0.6.18     2018-10-10 [1] CRAN (R 3.5.0)
 fs                  1.2.7      2019-03-19 [1] CRAN (R 3.5.2)
 glue                1.3.1      2019-03-12 [1] CRAN (R 3.5.2)
 magrittr            1.5        2014-11-22 [1] CRAN (R 3.5.0)
 memoise             1.1.0      2017-04-21 [1] CRAN (R 3.5.0)
 packrat             0.5.0      2018-11-14 [1] CRAN (R 3.5.0)
 pkgbuild            1.0.3      2019-03-20 [1] CRAN (R 3.5.2)
 pkgload             1.0.2      2018-10-29 [1] CRAN (R 3.5.0)
 prettyunits         1.0.2      2015-07-13 [1] CRAN (R 3.5.0)
 processx            3.3.0      2019-03-10 [1] CRAN (R 3.5.2)
 ps                  1.3.0      2018-12-21 [1] CRAN (R 3.5.0)
 R6                  2.4.0      2019-02-14 [1] CRAN (R 3.5.2)
 Rcpp                1.0.1      2019-03-17 [1] CRAN (R 3.5.2)
 remotes             2.0.4      2019-04-10 [1] CRAN (R 3.5.2)
 rlang               0.3.4      2019-04-07 [1] CRAN (R 3.5.2)
 rprojroot           1.3-2      2018-01-03 [1] CRAN (R 3.5.0)
 rstudioapi          0.10       2019-03-19 [1] CRAN (R 3.5.2)
 sessioninfo         1.1.1      2018-11-05 [1] CRAN (R 3.5.0)
 testthat            2.0.1      2018-10-13 [1] CRAN (R 3.5.0)
 usethis             1.5.0      2019-04-07 [1] CRAN (R 3.5.2)
 withr               2.1.2      2018-03-15 [1] CRAN (R 3.5.0)

```

### LINKED ISSUE #5479: Change in column "types" as a result of applying column filters
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.1578 (latest RStudio preview)
    OS Version      : Server, Ubuntu 16.04.6 LTS, Xenial
    R Version       : 3.6.0

### Steps to reproduce the issue:
- Import a csv file by clicking on it in the file pane.
- Change the default _type_ of one of the columns while the dataset is being imported.
- Once the dataset is imported and (automatically) viewed, use the column filter to select a subset of columns using their indices – including the column whose _type_ was customized.
- It can be seen that the column _type_ no longer matches the selected (customized) type. (It seems like it goes back to the automatically inferred _type_.) The way I could tell that was the following. I forced a column whose values looked _integer_ to be imported as a _character_ column. Later, when I tried to apply a row-filter to that column, a histogram was shown which signals the column _type_ was assumed to be numeric.

### LINKED ISSUE #5851: Data viewer fails to display data frames in list columns above column 50
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5019
    OS Version      : Windows 10 x64 (build 17763)
    R Version       : 3.6.1

### Steps to reproduce the problem

1. Create a data frame with 51 columns. The last column should be a list containing a small data frame:
```
foo <- as.data.frame(matrix(NA, ncol = 50, nrow = 1))
foo$list_col <- list(data.frame(a = 1:2, b = 3:4))
```
2. Run `View(foo)` to open the data frame in the data viewer.
3. Scroll to the right and click on the little arrows to see column 51.
4. Click on the little data frame in column 51.

### Describe the problem in detail
A new tab opens but it just shows a single `NA`. The console prints this: `View(foo[[50]][[1]])`

### Describe the behavior you expected
Instead of the NA I wanted to see the small data frame. Same as when running `View(foo[[51]][[1]])`.
I only encountered this problem when the list was column 51 or above. Compare with this:
```
bar <- foo[, c(51, 1:50)]
View(bar)
```
Here the list is the first column and clicking on the small data frame inside it works correctly.

### PR DESCRIPTION
**Pull request by adamconroy**
There were a number of bugs that happened as part of the initial columnOffset feature added to the data viewer. As part of this work I found a couple more bugs/oddities that I logged (#6147 #6150) that I couldn't fix as quickly here.

Fixes #5851 
Fixes #5479
Fixes #4682

### CODE REVIEW

File: src/cpp/session/resources/grid/dtviewer.js [hunk 1]
```diff
@@ -772,6 +772,16 @@ var invokeFilterPopup = function (ele, buildPopup, onDismiss, dismissOnClick) {
 };
 
 var createFilterUI = function(idx, col) {
+
+  // the index coming into this function is for absolute data purposes
+  // since this is a visual-centric function we operate based on the visible index
+  var visualIndex = idx -= columnOffset;
```
Comment (kevinushey) [inline src/cpp/session/resources/grid/dtviewer.js]: Is it intentional to assign the result of `idx -= columnOffset` here? I'd personally prefer to see this as separate statements since it's difficult to read as-is.

Comment (adamconroy) [reply src/cpp/session/resources/grid/dtviewer.js]: Nope! I would never do that intentionally, good catch. I originally was just using a shifted `idx` but added in the `visualIndex` later to be more clear and guess I missed the `-=`.

File: src/cpp/session/resources/grid/datatables/js/jquery.dataTables.min.js [hunk 2]
```diff
@@ -1 +1,4 @@
...),l.detach(),c.detach(),e.aaSorting=[],e.aaSortingFixed=[],ee(e),U(f).removeClass(e.asStripeClasses.join(" ")),U("th, td",i).removeClass(n.sSortable+" "+n.sSortableAsc+" "+n.sSortableDesc+" "+n.sSortableNone),e.bJUI&&(U("th span."+n.sSortIcon+", td span."+n.sSortIcon,i).detach(),U("th, td",i).each(function(){var t=U("div."+n.sSortJUIWrapper,this);U(this).append(t.contents()),t.detach()})),!h&&t&&t.insertBefore(r,e.nTableReinsertBefore),u.children().detach(),u.append(f),l.css("width",e.sDestroyWidth).removeClass(n.sTable),(a=e.asDestroyStripes.length)&&u.children().each(function(t){U(this).addClass(e.asDestroyStripes[t%a])});var d=U.inArray(e,F.settings);-1!==d&&F.settings.splice(d,1)})}),F.version="1.10.4",F.settings=[],F.models={},F.models.oSearch={bCaseInsensitive:!0,sSearch:"",bRegex:!1,bSmart:!0},F.models.oRow={nTr:null,anCells:null,_aData:[],_aSortData:null,_aFilterData:null,_sFilterRow:null,_sRowStripe:"",src:null},F.models.oColumn={idx:null,aDataSort:null,asSorting:null,bSearchable:null,bSortable:null,bVisible:null,_sManualType:null,_bAttrSrc:!1,fnCreatedCell:null,fnGetData:null,fnSetData:null,mData:null,mRender:null,nTh:null,nTf:null,sClass:null,sContentPadding:null,sDefaul
```
Comment (jmcphers) [inline src/cpp/session/resources/grid/datatables/js/jquery.dataTables.min.js]: Since this file is minified I can't tell what's changed here. Did you make an actual change or is this an artifact of some kind?

Comment (adamconroy) [reply src/cpp/session/resources/grid/datatables/js/jquery.dataTables.min.js]: The change is visible in `jquery.dataTables.js` that lives alongside the minified version.

Comment (jmcphers) [reply src/cpp/session/resources/grid/datatables/js/jquery.dataTables.min.js]: Ah, right! 🤦‍♂

**Comment by SimonDedman** [comment]
Good stuff guys! :thumbsup:

**Comment by ahcyip** [comment]
thanks for fixing this bug! https://github.com/rstudio/rstudio/issues/7802
