### PR TITLE
ensure errno loaded from msvcrt when checking iconv success

### LINKED ISSUE #2315: RStudio silently fails to save UTF-8 documents on Windows
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.353
    OS Version      : Windows 10 64bit
    R Version       : R 3.4.3

### Steps to reproduce the problem

With no project open, create a document with the contents:

```
鬼鬼鬼
鬼鬼鬼
鬼鬼鬼
```

Then, attempt to save the document with <kbd>Ctrl + S</kbd>.

### Describe the problem in detail

RStudio seems to indicate that the document was successfully saved, but the file on the filesystem is actually blank.

### Describe the behavior you expected

RStudio should save the file, or at least warn that the save failed because it failed to convert to the requested encoding.

### Notes

This is the RPC RStudio attempts to execute:

screen shot 2018-03-03 at 1 05 44 pm

With RStudio v1.1, the IDE does warn that the save attempt failed:

> Not all of the characters in ~/scratch/ouch.txt could be encoded using ISO8859-1. To save using a different encoding, choose "File | Save with Encoding..." from the main menu.

And the characters are replaced with `???` markers instead.

### PR DESCRIPTION
**Pull request by kevinushey**
This should fix #2315.

---

Some background: it looks like `Riconv.dll` imports `msvcrt.dll`, and uses `_errno` from there. On the other hand, `rsession` is getting it from a different runtime altogether: `api-ms-win-crt-runtime-l1-1-0.dll`, which I believe is required for applications built with MSVC 2015 + Qt.

One alternative way of approaching this would be to attempt to link directly with `msvcrt.dll`, but I'm not sure if this would work with MSVC + Qt (although this may be worth exploring if we're not a fan of this solution).

We might want to wrap this up into something cleaner, and make it clear that when calling R APIs that set `errno` we need to explicitly grab it from `msvcrt.dll`.

### CODE REVIEW

**Comment by kevinushey** [comment]
We should probably audit our usages of `errno` to check whether they're being set by R versus a Windows system call, since we'll need to use this 'hack' to ensure we're reading the right `errno`.

File: src/cpp/r/RUtil.cpp [hunk 1]
```diff
@@ -39,6 +39,20 @@ namespace rstudio {
 namespace r {
 namespace util {
 
+namespace {
+int* s_pErrorNumber;
+} // end anonymous namespace
+
+int errorNumber()
+{
+   return *s_pErrorNumber;
```
Comment (jmcphers) [inline src/cpp/r/RUtil.cpp]: This will dereference uninitialized memory if `setErrorNumber` is not called, which isn't likely but looks possible if an error occurs while trying to hook it up. How about init'ing the pointer to `nullptr` and returning a safe error number (0?) when the pointer is not initialized?

**Comment by kevinushey** [comment]
Should be good to go now -- I refactored much of the gunk into a separate file / class, and also added `R_ERRNO` in case we need to ever be conscious of the difference between the system-used `errno` and the R-used `errno`.
