### PR TITLE
Fix bug where replace errors did not appear with the correct file

### LINKED ISSUE #6519: Global replace for multiple files associates unwritable errors with the wrong file
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.3.923
    OS Version      : MacOS 10.15.4 and Red Hat 7.8
    R Version       : 3.6.3

### Steps to reproduce the problem

1. Create a couple of files, `file_444.txt` and `file_777.txt`, with a common string in them.
2. Give one of the files read-only permissions, `chmod 444 file_444.txt`. This file will not be affected.
3. Give the other file all permissions, `chmod 777 file_777.txt`. This file will get changed.
4. In RStudio, Edit -> Find in Files and search for the text.
5. Replace the text.

### Describe the problem in detail

The output will show an error because of the read-only file, since it can't be modified. However, the error is associated with the wrong file—it shows up in the Find in Files pane as if the writing failed with the writable file (`file_777`). Meanwhile, the record for the read-only file (`file_444.txt`) just has the original text, without replacement text.

file_failure

### Describe the behavior you expected

1) The error should be associated with the file that failed.
2) The last entry should include the replacement text.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### PR DESCRIPTION
**Pull request by melissa-barca**
Fixes #6519 
Updated error handling so that one json array of error strings is sent per every result found, even if no errors were found.

### CODE REVIEW

File: src/cpp/session/modules/SessionFind.cpp [hunk 1]
```diff
@@ -1002,17 +1002,29 @@ class GrepOperation : public boost::enable_shared_from_this<GrepOperation>
             matchOffs.push_back(matchOff);
             replaceMatchOns.push_back(replaceMatchOn);
             replaceMatchOffs.push_back(replaceMatchOff);
-            for (std::string newError : errorMessage)
-               errors.push_back(json::Value(newError));
+            {
```
Comment (jmcphers) [inline src/cpp/session/modules/SessionFind.cpp]: Why are these statements in a block?

Comment (melissa-barca) [reply src/cpp/session/modules/SessionFind.cpp]: I have a habit (from style guidelines in a past life) of scoping variables only used for a line or two. In this case it really doesn't matter since the scope ends two lines later so I removed the block.

**Comment by jmcphers** [comment]
It looks like this makes the `errors` object an array of arrays instead of an array of strings. If that's correct, does the client need to be updated?

https://github.com/rstudio/rstudio/blob/c7493e74141d87f6f13ee7cfd96f376dff406f1f/src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/model/FindResult.java#L114-L117

**Comment by melissa-barca** [comment]
> It looks like this makes the `errors` object an array of arrays instead of an array of strings. If that's correct, does the client need to be updated?
> 
> https://github.com/rstudio/rstudio/blob/c7493e74141d87f6f13ee7cfd96f376dff406f1f/src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/model/FindResult.java#L114-L117

Yes, errors is now an array of arrays. However, at this point the `results` object has been parsed out into individual `FindResult` objects (see below) - so at this point errors is an array of strings.`String getJavaStringArray(String)` calls `JsStringArray getStringArray(String property)` which turns the array into a string. The original code was calling the `getStringArray` method but actually was only parsing a string. https://github.com/rstudio/rstudio/blob/c7493e74141d87f6f13ee7cfd96f376dff406f1f/src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/events/ReplaceResultEvent.java#L41-L44

**Comment by jmcphers** [comment]
Okay, makes sense!
