### PR TITLE
Change default sqlite database path from /var/run to /var/lib to ensure it is not deleted on reboot

### LINKED ISSUE #6706: Database files stored in `/var/run`
### System details

    RStudio Edition : Server
    RStudio Version :  1.4.221

### Steps to reproduce the problem

1. Start RStudio server.
2. Look in `/var/run/rstudio-server`.

### Describe the problem in detail

RStudio's database is stored there, in `rstudio.sqlite`. 

https://github.com/rstudio/rstudio/blob/e0f24229233f3dddba00d854e2487d4e366dfc4e/src/cpp/server_core/ServerDatabase.cpp#L42

This probably isn't where we want it because `/var/run` is intended to store ephemeral data that does not survive reboots.

> Files under this directory must be cleared (removed or truncated as appropriate) at the beginning of the boot process.

http://www.pathname.com/fhs/pub/fhs-2.3.html#VARRUNRUNTIMEVARIABLEDATA

### Describe the behavior you expected

Because this database stores state that is meant to survive reboots, it should be stored somewhere else. We might consider `/var/lib` where we already store e.g. nginx conf, or respecting `XDG_DATA_DIRS`.

### PR DESCRIPTION
**Pull request by kfeinauer**
Let me know if you think this indeed does need the XDG treatment. Reading through the spec it looked to me like there was only a concept for a user data dir, not a system data dir, so I've forgone the XDG treatment.

Fixes #6706

### CODE REVIEW

**Comment by kfeinauer** [comment]
Note: update pro docs upon merging

File: src/cpp/server_core/include/server_core/ServerDatabase.hpp [hunk 1]
```diff
@@ -16,23 +16,21 @@
...
+#include <boost/optional.hpp>
+
 #include <core/Database.hpp>
+
 #include <shared_core/Error.hpp>
+#include <shared_core/system/User.hpp>
 
 namespace rstudio {
-
-namespace core {
```
Comment (MariaSemple) [inline src/cpp/server_core/include/server_core/ServerDatabase.hpp:24]: Is it safe to remove the `#include <shared_core/Error.hpp>` rather than the forward declaration? It's not too important, since we'd just end up including `Error.hpp` pretty much everywhere, but I definitely have a preference for forcing each file to explicitly include all the files it needs.

**Comment by jmcphers** [comment]
There's `XDG_DATA_DIRS` for the data directories. However:

1. we haven't migrated anything else away from `/var/lib` so there's not much harm in storing more there;
2. there is currently no accessor in `Xdg.cpp` for `XDG_DATA_DIRS`; and
3. the primary benefit of XDG in this kind of context is that it lets you load data from a location of your choice, and that's already implemented here. 

I will open an issue generally to store persistent global state in XDG_DATA_DIRS but it's pretty low priority and no need to frontload it here.

File: src/cpp/server_core/include/server_core/ServerDatabase.hpp (hunk 1 above)
Comment (kfeinauer) [reply src/cpp/server_core/include/server_core/ServerDatabase.hpp:24]: We already had a full declaration in this header file, so I just removed the forward decl (it was already declared).
