### PR TITLE
don't monitor renv / packrat libraries

### LINKED ISSUE #3267: Don't add inotify watches on project libraries.
One of my favorite RStudio features is sometimes broken.

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.442
    OS Version      : Ubuntu 18.04
    R Version       : 3.4.4

### Steps to reproduce the problem
Open a project
### Describe the problem in detail
Sometimes after opening a project the following error appears in the console:

    Warning message:
    File monitoring failed for project at "~/Documents/Projects/mk_waste"
    Error 28 (No space left on device)
    Features disabled: R source file indexing, Diagnostics

The log in `.rstudio-desktop/log/rsession-user.log` is:

    06 Aug 2018 10:52:25 [rsession- user] ERROR system error 28 (No space left on device) [path=/home/ user/.rstudio-desktop/monitored]; OCCURRED AT: rstudio::core::Error rstudio::core::system::file_monitor::{anonymous}::addWatch(const rstudio::core::FileInfo&, const rstudio::core::FilePath&, bool, int, rstudio::core::system::file_monitor::{anonymous}::Watches*) /home/ubuntu/rstudio/src/cpp/core/system/file_monitor/LinuxFileMonitor.cpp:226; LOGGED FROM: void rstudio::session::module_context::{anonymous}::onMonitoringError(const rstudio::core::Error&) /home/ubuntu/rstudio/src/cpp/session/SessionModuleContext.cpp:507
### Describe the behavior you expected
No error to appear when projects are opened and go to file/function to work. At the moment this does work sometimes but I can't tell what the pattern is.

Needless to say that I have plenty of space on my /home drive (> 5GB). Restarting RStudio never works as far as I can tell. Rebooting Ubuntu does.

I'd include a diagnostic report but that would contain file paths which I'd rather not disclose. All files are local.

### PR DESCRIPTION
**Pull request by kevinushey**
Closes #3267.

### CODE REVIEW

File: src/cpp/core/include/core/FileInfo.hpp [hunk 1]
```diff
@@ -89,7 +89,7 @@ class FileInfo
    }
    
 public:
-   std::string absolutePath() const { return absolutePath_.c_str(); }
+   const std::string& absolutePath() const { return absolutePath_; }
```
Comment (gtritchie) [inline src/cpp/core/include/core/FileInfo.hpp]: Why this change? Isn't it generally risky to return a reference to a class member? Since you then just do `c_str()`, anyways, why not keep it the same? Performance?

File: src/cpp/core/FileInfo.cpp [hunk 2]
```diff
@@ -43,6 +43,8 @@ FileInfo::FileInfo(const std::string& absolutePath,
       lastWriteTime_(0),
       isSymlink_(isSymlink)
 {
+   // some file paths might be constructed with trailing nul bytes; remove those here
```
Comment (gtritchie) [inline src/cpp/core/FileInfo.cpp]: Out of curiosity, what's resulting in trailing `\0` s?

File: src/cpp/session/projects/SessionProjectContext.cpp [hunk 3]
```diff
@@ -477,12 +477,13 @@ void ProjectContext::onDeferredInit(bool newSession)
                             this, _1);
    cb.onUnregistered = bind(&ProjectContext::fileMonitorTermination,
                             this, Success());
+
+   bool hideObjectFiles = prefs::userPrefs().hideObjectFiles();
```
Comment (jmcphers) [inline src/cpp/session/projects/SessionProjectContext.cpp]: What do you think about adding another pref (with no UI) whose value is an array of additional directories to exclude from monitoring? Realize the ideal solution is more along the lines of a `.ignore` file, but as that's unlikely to land in 1.3 it'd be nice to have an escape hatch for cases where something besides the hardcoded list needs to be excluded.

File: src/cpp/core/include/core/FileInfo.hpp (hunk 1 above)
Comment (kevinushey) [reply src/cpp/core/include/core/FileInfo.hpp]: Right, the old implementation was forcing a copy every time we requested the absolute path of a FileInfo object:

- We call `.c_str()`, returning a `const char*`,
- That's implicitly converted to `std::string`, constructing a new `std::string` from that C string,
- That also implies finding the null terminator when constructing that new `std::string`.

Returning a const-ref is risky, since it implies someone could store a reference that outlives the parent object. I'll change this back to return a plain `std::string` -- at least then we're still just creating a `std::string` from a `std::string` and the compiler is likely to optimize any copies away anyhow.

File: src/cpp/core/FileInfo.cpp (hunk 2 above)
Comment (kevinushey) [reply src/cpp/core/FileInfo.cpp]: I had this change in my mind (although this should be fixed now):

https://github.com/rstudio/rstudio/commit/1e3bed6b8034584a0d462e5c550af9fbf0440d18

But the fact that we were calling `.c_str()` before made me think we need to be cautious about any other potential strings coming in with trailing null bytes.

File: src/cpp/session/projects/SessionProjectContext.cpp (hunk 3 above)
Comment (kevinushey) [reply src/cpp/session/projects/SessionProjectContext.cpp]: That sounds like a good idea to me as well -- it'd be nice to have as an escape hatch.

File: src/cpp/core/FileInfo.cpp (hunk 2 above)
Comment (gtritchie) [reply src/cpp/core/FileInfo.cpp]: I'm still not clear on this; a `std::string` initialized from a C string (e.g. `char *`) always stores the trailing \0. So I think absolutePath_ = absolutePath_.c_str() is a noop?

Comment (kevinushey) [reply src/cpp/core/FileInfo.cpp]: Right :-) And we were constructing strings with a length in that particular spot, and I recall seeing that this was actually something like a "size of allocated space for file path" rather than "actual length of file path" in some caes.

**Comment by kevinushey** [comment]
Now with a user preference allowing users to add their own custom exclusions.
