### PR TITLE
avoid global binding for snippet insertion

### LINKED ISSUE #3790: snippets are duplicated when inserted with Shift+Tab
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1079
    OS Version      : macOS 10.14
    R Version       : 3.5.1

### Steps to reproduce the problem

In an R document, on a blank line, try typing:

    ts<Tab>

### Describe the problem in detail

The timestamp snippet is executed twice, such that output in the document is e.g.

```
# Wed Oct 31 09:32:28 2018 -----------------------------# Wed Oct 31 09:32:28 2018 ------------------------------
```

### Describe the behavior you expected

The snippet should only be inserted once.

### PR DESCRIPTION
**Pull request by kevinushey**
Fixes #3790.

The completion managers we define for languages that support snippet insertion already handle Shift + Tab for snippet insertion; see e.g.

https://github.com/rstudio/rstudio/blob/master/src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionManagerBase.java#L490-L499

Because of this, we no longer need the global command binding as this ultimately causes issues with double-insertion of snippets.

I also discovered that the 'handlesEventPropagation' item doesn't work as expected -- `Event.getCurrentEvent()` doesn't actually return the current live event, because the command is executed in response to a GWT-generated _preview_ event, which GWT unfortunately doesn't make available. (https://developer.mozilla.org/en-US/docs/Web/API/Window/event does exist, but its use is in general not recommended, although for reasons that are not completely obvious to me)

### CODE REVIEW

File: src/gwt/src/org/rstudio/core/rebind/command/ShortcutsEmitter.java [hunk 1]
```diff
@@ -206,11 +203,6 @@ else if (keys.size() == 2)
          throw new UnableToCompleteException();
       }
       
-      if (handlesEventPropagation.equals("true"))
-      {
-         writer.println("ShortcutManager.INSTANCE.registerCommandHandlesEventPropagation(" + command + ");");
```
Comment (jmcphers) [inline src/gwt/src/org/rstudio/core/rebind/command/ShortcutsEmitter.java]: It looks like this is the only caller of `registerCommandHandlesEventPropagation`. Can we remove that method, too (and any other now-dead infrastructure?)

Comment (kevinushey) [reply src/gwt/src/org/rstudio/core/rebind/command/ShortcutsEmitter.java]: Yes -- I'll take that out.
