### PR TITLE
Exception in Find in Files dialog

### LINKED ISSUE #6085: Exception in Find in Files dialog
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.773

### Repro

Not 100% sure, but suspect that it occurs when we close the Find in Files dialog while we are waiting for preview results to come back.

### Describe the problem in detail

```
23 Jan 2020 00:08:21 [rserver] ERROR CLIENT EXCEPTION (rsession-jmcphers): (TypeError) : null is not an object (evaluating '(nIw[b]='128',a).resultsCount=0');
org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.java#128::clearResultsCount
org/rstudio/studio/client/workbench/views/output/find/FindOutputPresenter.java#466::initialize
org/rstudio/studio/client/workbench/views/output/find/FindOutputTab_Shim__Impl.java#79::onSuccess2
org/rstudio/studio/client/workbench/views/output/find/FindOutputTab_Shim__Impl.java#65::execute
org/rstudio/core/client/AsyncShim.java#92::preInstantiationHook
org/rstudio/studio/client/workbench/views/output/find/FindOutputTab_Shim__Impl.java#63::onSuccess
```

### Describe the behavior you expected

No exception. We probably need a null guard here (unless this is suggestive of a deeper issue):

https://github.com/rstudio/rstudio/blob/46f6e09c13285b121062782e122f555b854a5a1f/src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPresenter.java#L249-L251

### PR DESCRIPTION
**Pull request by melissa-barca**
Fixes #6085 

This PR fixes an issue where the find result count was being cleared on initialization of the Find In Files dialog, causing this information to be lost from the state when a new rsession started. 
It also prevents any calls to clear the result count from causing an exception when the result count is null.

### CODE REVIEW

File: src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.java [hunk 1]
```diff
@@ -126,7 +126,8 @@ public native final int getResultsCount() /*-{
       }-*/;
 
       public native final void clearResultsCount() /*-{
-         this.resultsCount = 0;
+         if (this.resultsCount !== null)
```
Comment (jmcphers) [inline src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.java]: The exception was happening when `this` is `null`, so it would still happen here. I think we need to either (a) check `dialogState_` for null upstream, or (b) check `this` itself here.

Comment (melissa-barca) [reply src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.java]: Ok, that makes sense. I added an upstream check to the only place it makes sense for dialogState_ to be null.
