### PR TITLE
only trigger external edit checks when focused (closes #3554)

### LINKED ISSUE #3554: "File changed" dialog prompts once per observed edit
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.2.1009
    OS Version      : macOS Mojave 10.14
    R Version       : 3.5.1

### Steps to reproduce the problem

* Open a file in an IDE editor pane.
* Make an edit to that file but do not save.
* In your favorite non-RStudio editor, open that same file.
* Within that alternate editor, repeatedly make changes to the file then save your changes.
* Switch back to the IDE.

### Describe the problem in detail

The "File changed" dialog appears, allowing the user to optionally discard the edits in the IDE, as the file on-disk has changed. Choose to reload and discard.

screen shot 2018-09-27 at 10 16 35 pm

The file-changed dialog appears multiple times - once per save operation by the other editor?

### Describe the behavior you expected

Only one "File Changed" dialog; multiple saves do not demand multiple dialog displays.

### PR DESCRIPTION
**Pull request by kevinushey**
Note that an external edit check is always triggered when the window is focused, so effectively this PR ensures that 'file changed' events are only shown to the user after they re-focus the IDE instance.

### CODE REVIEW

**Comment by jmcphers** [comment]
Before this change, if you open a file in an external editor and it isn't dirty in RStudio, then saving in the external editor will cause it to automagically reload in RStudio with the new contents. After this change that won't happen any more.

This also requires that the document *itself* have focus, which might not be what you want. For example, if you alt-tab back to RStudio from your external editor, and focus lands on the R Console tab, the contents in the Source pane will continue to look stale indefinitely (if I'm reading this correctly).

I think we should avoid touching the polling logic and instead add some guards that prevent the external edit check from being re-executed when the last external edit check is still unresolved (e.g. waiting for the user to respond).

File: src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java [hunk 1]
```diff
@@ -1558,10 +1558,8 @@ else if (!fileChange.getFile().getPath().equals(getPath()))
                return;
 
             // always check for changes if this is the active editor
-            if (commandHandlerReg_ != null)
-            {
+            if (isActiveDocument())
```
Comment (kevinushey) [inline src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java]: Note that `isActiveDocument()` is a helper function that does exactly this check, so this change just ensures we reuse that utility function.
