### PR TITLE
Verify connection state of PostgreSQL connection pooled connection and re-establish if necessary

### LINKED ISSUE #8266: Pooled PostgreSQL connections forever unusable if database connections are lost
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.969-1

### Steps to reproduce the problem

1. Configure RStudio to use the PostgreSQL database backend
2. Start the service
3. Stop the PostgreSQL database service
4. Attempt to sign in / sign out. Note that you cannot - this is expected since the database is down.
5. Restart PostgreSQL service
6. Notice you still cannot sign in / out, even though the DB is back up.

### Describe the problem in detail

Connection failures are a final state - the database connections are forever lost once connectivity is initially lost.

### Describe the behavior you expected

Database connections should reconnect.

### PR DESCRIPTION
**Pull request by kfeinauer**
### Intent

Currently, database connections are not re-established if they go defunct, such as if the upstream PostgreSQL database stops or due to transient network failure. We should restart these connections automatically.

See #8266 for more detail.

### Approach

Whenever a connection is requested from the pool, quickly check to see if the state is open by running a very simple efficient query. If not, attempt to re-establish this connection, but only once. If we do re-establish the connection, use it instead of the old connection.

Fixes #8266

### QA Notes

See #8266

### CODE REVIEW

File: src/cpp/core/Database.cpp [hunk 1]
```diff
@@ -563,6 +563,42 @@ std::string PooledConnection::driverName() const
...
+   // so any errors on the file handle itself we do not want to gracefully recover from, as they would
+   // indicate a very serious programming error
+   if (connection->driver() == Driver::Sqlite)
+      return;
+
+   // it is possible for connections to go stale (such as if the upstream connection is closed)
+   // which will prevent it from being usable - we test for this by running a very efficient query
+   // and checking to make sure that no error has occurred
+   Error error = connection->executeStr("SELECT 1");
+   if (!error)
```
Comment (jmcphers) [inline src/cpp/core/Database.cpp:583]: Two questions here...
1) Do we want to preserve/log the error which caused us to attempt a reconnect?
2) Do we always want to reconnect regardless of the error returned? (i.e. are there some errors which are unrecoverable?)

Comment (ricardofandrade) [reply src/cpp/core/Database.cpp:583]: @kfeinauer Is there any reason why we can't use that list of recoverable Postgres errors that RSC uses here?
Another thing, could we preserve the last error that happened in the database connection instead of having to execute a new query?

Comment (kfeinauer) [reply src/cpp/core/Database.cpp:583]: We need to execute this query whenever a connection is taken from the pool to make sure it is still alive. Unfortunately, the error codes that are returned by SOCI do not properly indicate if we had a connection issue - SOCI only returns that an `Unknown` error occurred on the connection. I verified this while testing - my original implementation depended on checking for that particular error state and re-opening the connection just for that error.

However, since `SELECT 1` should always succeed on a valid connection, this appears to be the most efficient way to determine that a connection error has actually occurred.

@jmcphers I will go ahead and log the original `SELECT 1` error - this will clutter the logs a little bit, but this should be a fairly rare occurrence and give us more diagnostic info should we need it.

Comment (ricardofandrade) [reply src/cpp/core/Database.cpp:583]: @kfeinauer It recall it was possible to "unwrap" the original Postgres error code. I think I used this:
https://github.com/SOCI/soci/blob/d4d50d65002ec2fb1486622634c31234b5f05686/src/backends/postgresql/error.cpp#L52
Look a little above that. You'll see that SOCI itself does some error classification. It don't quite match the one used in RSC though.

The reason why it's important to decide between recoverable and unrecoverable errors is that we shouldn't insist in reconnecting if the error is permanent, the service should stop. Insisting could throw the entire instance(s) in an undefined behavior state (functional, not in the C++ sense) potentially causing other problems or misleading users/admins. @jmcphers I'll let you make the call whether this is important for 1.4.

+1 for logging the `SELECT 1` error. But if we stop on unrecoverable errors, there won't be that many logs.

Comment (kfeinauer) [reply src/cpp/core/Database.cpp:583]: I don't agree that we need to specifically look at the postgres error code here, and it would be more code to propagate that.

If you cannot successfully execute `SELECT 1`, then it's a connection issue. I think checking each and every error code like is done in the Connect case is a bit overkill here: https://github.com/rstudio/connect/blob/87ca7e50260fd48755101d4ed94dc509c22b965a/src/connect/store/store.go#L646. Certainly, encountering a scenario where there is a truly unrecoverable database error is very exceptional. 

Also, running sessions do not need database access to function properly - it's only needed to sign new users into the system. Stopping RSP entirely because of a database failure seems overkill to me, considering the vast majority of our product doesn't care if there's a database or not.

Comment (kfeinauer) [reply src/cpp/core/Database.cpp:583]: I also do not know from looking at the sample code and the `postgresql_soci_error` code specifically how these error codes map and should exactly be handled. That introduces more uncertainty into the code than I am comfortable with at this point in the release.

**Review by jmcphers — APPROVED** [review]

**Review by ricardofandrade — APPROVED** [review]
The reconnection should suffice for now.
We can take a look at error handling later on.
Let's 🚢 it!
