### PR TITLE
Do not attempt to continue logging session output dp fd writes if the read end of the pipe closes

### LINKED ISSUE #8082: Broken pipe errors from stream capture thread can fill disk quickly
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.1073

### Steps to reproduce the problem

Run a command in R which streams a lot of output, then do something that breaks the file descriptors that capture the output streams (we don't know how this happens)

Originally from https://rstudioide.zendesk.com/agent/tickets/53571.

### Describe the problem in detail

The logs are quickly overwhelmed with errors that look like this: 

```
ERROR system error 32 (Broken pipe); OCCURRED AT rstudio::core::system::{anonymous}::standardStreamCaptureThread(int, int, const rstudio_boost::function<void(const std::basic_string<char>&)>&, int, int, const rstudio_boost::function<void(const std::basic_string<char>&)>&)::__lambda0 src/cpp/core/system/PosixOutputCapture.cpp:78; LOGGED FROM: rstudio::core::system::{anonymous}::standardStreamCaptureThread(int, int, const rstudio_boost::function<void(const std::basic_string<char>&)>&, int, int, const rstudio_boost::function<void(const std::basic_string<char>&)>&)::__lambda0 src/cpp/core/system/PosixOutputCapture.cpp:78
```

These can fill up a disk quickly enough to crash the server and have been observed doing so.

### Describe the behavior you expected

We already specifically exclude `EAGAIN` and `EINTR` from this error logging, possibly for similar reasons.

https://github.com/rstudio/rstudio/blob/f23c1df50290b9e6f2bd9b2ecebca19b1c39bbf0/src/cpp/core/system/PosixOutputCapture.cpp#L76-L81

We should make sure this can't happen by:

- Also suppressing `EPIPE`, and/or
- Suppressing multiple instances of the same error being logged back to back (or some other cool-off mechanism)

### PR DESCRIPTION
**Pull request by kfeinauer**
### Intent

Whenever the read end of the dup fd pipe closes, we continuously try to write to the pipe, but it will never succeed again. We should stop attempting to write in this case, and only log an error once.

It is currently unknown how this situation can occur, but it is happening for a user of Slurm sessions: see Zendesk ticket _53571_.

### Approach

If a pipe error (or FD is closed), stop trying to write to it. Only log the error once and explain that output will no longer be redirected.

Fixes #8082

### QA Notes

We are unable to reproduce this as of yet. We should ask the customer in the Zendesk ticket to verify the fix.

### CODE REVIEW

**Comment by kfeinauer** [comment]
@jmcphers @mikebessuille This PR is left without a milestone for now - not sure we want to slam it in to 1.4. However, this appears to be a pretty big issue for the customer. We will need to follow up / see how that support issue progresses before deciding if this will need to be in 1.4 IMO.

**Comment by mikebessuille** [comment]
Sounds like something I'd be inclined to put into 1.4, if you feel the fix is safe and clearly fixes the problem.

**Comment by kfeinauer** [comment]
@mikebessuille yes, that is the plan. Though the fact I cannot reproduce causes some testing uncertainty, but the scope of the fix is quite small.

File: src/cpp/core/system/PosixOutputCapture.cpp [hunk 1]
```diff
@@ -71,21 +72,48 @@ void standardStreamCaptureThread(
...
+                // the std stream was closed somehow, meaning this write call will never succeed again
+                // mark that we should skip the write, and only log this error once
+                *pSkipWrite = true;
+
+                Error error = systemError(errno, ERROR_LOCATION);
+                std::string cause = errno == EBADF ? " closed" : "'s pipe read end closed";
+                std::string description =
+                      descriptorType + " descriptor " + core::safe_convert::numberToString(dupFd) +
+                      cause + ". Output will no longer be redirected.";
+                error.addProperty("description", description);
```
Comment (jmcphers) [inline src/cpp/core/system/PosixOutputCapture.cpp:96]: Nit: this can be set in the `systemError` constructor more succinctly

**Review by jmcphers — APPROVED** [review]

**Comment by MBeuttler** [comment]
Do you have a plan, when this fix will be shipped?
We at TRUMPF just run into this issue, too.
