### PR TITLE
Fix an issue where themes are sometimes not loaded due to incorrect relative paths.

### LINKED ISSUE #3295: data viewer no longer inherits dark themes
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.888
    OS Version      : macOS 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem

Try opening the Data Viewer with e.g.

```R
data <- as.data.frame(matrix(1:16, nrow = 4))
View(data)
```

### Describe the problem in detail

The data viewer elements are not styled.

### Describe the behavior you expected

The data viewer should adapt to dark themes.

Compare:

### RStudio v1.1

screen shot 2018-08-08 at 4 35 01 pm

### RStudio v1.2

screen shot 2018-08-08 at 4 34 07 pm

(for reference, I'm using Tomorrow Night Bright as the current theme)

### Notes

There is a JavaScript error indicating that we were unable to retrieve the associated `.rstheme` file in the gridviewer:

screen shot 2018-08-08 at 4 38 01 pm

### PR DESCRIPTION
**Pull request by MariaSemple**
When the URL ends with a "file" (e.g. grid.html) the "file" part should not be counted when determining how many levels to go up (with "../") for the theme link element.

Fixes #3295.

### CODE REVIEW

File: src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/AceThemes.java [hunk 1]
```diff
@@ -71,7 +71,11 @@ private void applyTheme(Document document, final AceTheme theme)
       if (!currentUrl.equals(baseUrl) &&
          currentUrl.indexOf(baseUrl) == 0)
       {
-         pathUpCount = currentUrl.substring(baseUrl.length()).split("/").length;
+         String[] urlElements = currentUrl.substring(baseUrl.length()).split("/");
+         if (urlElements[urlElements.length - 1].contains("."))
```
Comment (jmcphers) [inline src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/AceThemes.java]: I don't think this is foolproof, since there's no rule against directory names having dots; in the general case, there is no way for us to tell by looking at a URL string whether the last segment refers to a file or a directory. 

Do we really need the `"../"` construction at all? Now that the theme URL handler is at a predictable location, it seems like we could build the theme URL off the `baseUrl`, regardless of the `currentUrl`. What do you think?

Comment (MariaSemple) [reply src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/AceThemes.java]: Oh, and use an absolute link element rather than a relative one? That seems better to me, I'll test that.
