### PR TITLE
Fix verify installation errors

### LINKED ISSUE #7221: RStudio Server Preview 1.3.1045 fails to start
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.1045
    OS Version      : Ubuntu 18.04.4 LTS
    R Version       : 4.0.2

### Steps to reproduce the problem
* Install the preview version
```
wget https://s3.amazonaws.com/rstudio-ide-build/server/bionic/amd64/rstudio-server-1.3.1045-amd64.deb
sudo gdebi rstudio-server-1.3.1045-amd64.deb
```
### Describe the problem in detail
After upgrading no error message is returned on the terminal but it's not possible to open an RStudio session, the browser just keeps loading indefinitely. 

This is what I get after running `sudo rstudio-server verify-installation`

```
sudo rstudio-server verify-installation
25 Jun 2020 01:25:51 [rsession-rstudio-server] ERROR system error 13 (Permission                                                   denied) [path: /home/rstudio-server/.config/rstudio, target-dir: ]; OCCURRED AT                                                   rstudio::core::Error rstudio::core::FilePath::createDirectory(const string&) co                                                  nst src/cpp/shared_core/FilePath.cpp:648; LOGGED FROM: rstudio::core::Error rstu                                                  dio::session::prefs::initializePrefs() src/cpp/session/prefs/UserPrefs.cpp:142
25 Jun 2020 01:25:51 [rsession-rstudio-server] ERROR system error 13 (Permiso de                                                  negado) [path: /home/rstudio-server/.config/rstudio/dictionaries/custom, target-                                                  dir: ]; OCCURRED AT rstudio::core::Error rstudio::core::FilePath::createDirector                                                  y(const string&) const src/cpp/shared_core/FilePath.cpp:648; LOGGED FROM: rstudi                                                  o::core::Error rstudio::core::spelling::HunspellDictionaryManager::availableLang                                                  uages(std::vector<rstudio::core::spelling::HunspellDictionary>*) const src/cpp/c                                                  ore/spelling/HunspellDictionaryManager.cpp:158
25 Jun 2020 01:25:51 [rsession-rstudio-server] ERROR system error 13 (Permiso de                                                  negado) [path: /home/rstudio-server/.config/rstudio/dictionaries/custom, target-                                                  dir: ]; OCCURRED AT rstudio::core::Error rstudio::core::FilePath::createDirector                                                  y(const string&) const src/cpp/shared_core/FilePath.cpp:648; LOGGED FROM: std::v                                                  ector<std::__cxx11::basic_string<char> > rstudio::core::spelling::HunspellCustom                                                  Dictionaries::dictionaries() const src/cpp/core/spelling/HunspellCustomDictionar                                                  ies.cpp:33
```
If I downgrade to version 1.3.1039 everything goes back to normal

### Describe the behavior you expected

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### PR DESCRIPTION
**Pull request by kfeinauer**
The verify installation command was producing some directory creation errors because the server user that the session runs as in this case does not usually have a home directory. Fixed this by specifying a tmp dir for verify installation home directory. 

Also fixed a verify hang in pro by not doing first project template copying if in verify mode - otherwise, a project would be set, and project sharing initialization would run which would cause a hang as it connects back to rserver, which is not listening in verify mode.

Fixes #7221

### CODE REVIEW

File: src/cpp/server/ServerSessionManager.cpp [hunk 1]
```diff
@@ -382,12 +382,33 @@ Error launchSession(const r_util::SessionContext& context,
                     PidType* pPid)
 {
    // launch the session
+   // we use a modified configured home directory to provide a realiable temp dir that can be written to
```
Comment (jmcphers) [inline src/cpp/server/ServerSessionManager.cpp:385]:
```suggestion
   // we use a modified configured home directory to provide a reliable temp dir that can be written to
```

File: src/cpp/server/ServerSessionManager.cpp [hunk 2]
```diff
@@ -382,12 +382,33 @@ Error launchSession(const r_util::SessionContext& context,
...
+   else
+   {
+      error = tmpDir.ensureDirectory();
+      if (error)
+      {
+         LOG_ERROR(error);
+      }
+      else
+      {
+         config.environment.push_back(std::make_pair("XDG_CONFIG_HOME", tmpDir.getAbsolutePath()));
```
Comment (jmcphers) [inline src/cpp/server/ServerSessionManager.cpp:408]: Should this use setenv (so that it overrides any existing `XDG_CONFIG_HOME`)?

Comment (kfeinauer) [reply src/cpp/server/ServerSessionManager.cpp:408]: Good catch, will fix that.

**Comment by kfeinauer** [comment]
@jmcphers Updated, please review. Do we want to hold off on merging this until the Waterlily cutoff?

**Comment by jmcphers** [comment]
We aren't taking Water Lily changes (other than regressions) next week, but we are taking them today!
