### PR TITLE
Restore R version selection option for Win desktop

### LINKED ISSUE #2297: Can't select R version from Global Options on Windows daily build
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.2.374
    OS Version      :  Windows 7
    R Version       :  3.4.3

### Steps to reproduce the problem

Tools > Global Options > R version selector is missing

### Describe the problem in detail

In 1.1, you could select which version of R to run from the same setting:

image

### Describe the behavior you expected

Be able to select the setting from the same place in RStudio Desktop 1.2

### PR DESCRIPTION
**Pull request by gtritchie**
A lingering TODO from the QtWebEngine switchover.

Fixes #2297

### CODE REVIEW

File: src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java [hunk 1]
```diff
@@ -127,7 +127,10 @@ void promptForText(String title,
 
    void bringMainFrameToFront();
    void bringMainFrameBehindActive();
-   
+
+   void getRVersion(CommandWithArg<String> callback);
```
Comment (kevinushey) [inline src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java]: Maybe add a comment warning that these are currently only implemented for Windows?

Comment (gtritchie) [reply src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java]: Those have always been Windows-only, but sure, will add a comment.
