### PR TITLE
Maintain file permissions while performing replace

### LINKED ISSUE #6048: File properties aren't respected by global find and replace
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.3.743 & 1.3.730
    OS Version      : MacOS 10.15.3 & Red Hat 7.8
    R Version       : 3.6.1 & 3.6.0

### Steps to reproduce the problem

1. Create a file called `mischief.R` containing just one line, `Loki`.
2. On the command line: change the file permissions to read-only and a different (real) owner and group, e.g.
```
chmod 444 mishchief.R
chown another_user mishchief.R
chgrp another_group mishchief.R
```
3. Make sure that the permissions, owner, and group have been updated correctly, e.g.
```
# ls -l mischief.R 
-r--r--r--. 1 another_user another_group 5 Jan 17 18:58 mischief.R
```
3. In the IDE: Edit -> Find in Files
4. Under "Find" type `Loki`
5. Under "Search In" choose the directory containing the file `mischief.R`
6. Click on "Find"
    - The search should display the file name and location above, with _Loki_ highlighted in the matching lines
7. Next to "Replace With" type `Trickster`
8. Replace All -> Yes
    - The search should display the file name and location above, with _Trickster_ highlighted in the matching lines
9. On the command line, check the permissions, etc., on the file
    - Write permissions have been added to the file, and the owner and group have reverted to the user and group associated with the RStudio account
```
# ls -l mischief.R 
-rw-rw-r--. 1 rstudio rstudio 5 Jan 17 18:58 mischief.R
```
10. Check the contents of the file: _Loki_ is replaced with _Trickster_
```
[root@ip-10-0-0-42 global]# cat mischief.R 
Trickster
```

### Describe the problem in detail

The file has been updated, and its permissions, owner, and group have been changed.

### Describe the behavior you expected

The existing file properties should be respected:
1. File permissions, owner, and group should not be changed.
2. The file should not be changed, as it's not supposed to be writable.

----------

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### PR DESCRIPTION
**Pull request by melissa-barca**
Fixes #6048 

This PR fixes the global replace functionality so it no longer changes the file permissions where the replace takes place. Since we are using a temporary file to perform the replace, we save the permissions of the original file while initializing the replace, and set these permissions after overwriting the original file with the one containing the replace.

### CODE REVIEW

File: src/cpp/session/modules/SessionFind.cpp [hunk 1]
```diff
@@ -487,6 +489,42 @@ class GrepOperation : public boost::enable_shared_from_this<GrepOperation>
       }
    }
 
+   Error setPermissions(const std::string& filePath, boost::filesystem::perms permissions)
+   {
+      boost::filesystem::path path(filePath);
```
Comment (jmcphers) [inline src/cpp/session/modules/SessionFind.cpp]: When constructing a `boost::filesystem::path` from a `std::string`, some extra work is needed on Windows; see: https://github.com/rstudio/rstudio/blob/6a45dc8e1fd19a093a68bd5b0a533c34b10293b0/src/cpp/shared_core/FilePath.cpp#L224-L246

This is one reason that we almost never use raw `boost::filesystem::path` objects and instead always use our `FilePath` wrapper. You might consider making these set/get permissions methods part of the FilePath object itself (which stores a boost filesystem path internally).

Comment (melissa-barca) [reply src/cpp/session/modules/SessionFind.cpp]: At first I did have this as part of `FilePath`, but I felt weird having our wrapper functions directly pass and return `boost::filesystem::perms` without its own wrapper and implementing that seems like more work will little payoff. What are your thoughts on this?

Comment (jmcphers) [reply src/cpp/session/modules/SessionFind.cpp]: That's a good instinct; FilePath should abstract boost::filesystem completely so we shouldn't return filesystem internals like `perms`.

I think we could greatly simplify this by skipping all permissions-related code on Windows. The only permission supported by `boost::filesystem::perms` on Windows is write permission... which is a tautology here since we just wrote to the file! https://www.boost.org/doc/libs/1_66_0/libs/filesystem/doc/reference.html#Enum-perms

We could also simplify it further by using `::stat` and `::chmod` directly instead of using the Boost wrappers around them (which would remove the need to handle exceptions and path wrappers); but I'll leave that up to your discretion.

Comment (melissa-barca) [reply src/cpp/session/modules/SessionFind.cpp]: Hi Jonathan, at this point I can't think of a strong argument to use `::stat` and `::chmod` over the boost permissions. I updated the code so these functions are not declared or called in Windows. Thanks!

File: src/cpp/session/modules/SessionFind.cpp [hunk 2]
```diff
@@ -586,7 +586,14 @@ class GrepOperation : public boost::enable_shared_from_this<GrepOperation>
             outputStream_->flush();
             inputStream_.reset();
             outputStream_.reset();
+
+            // Unneccesary on Windows because this only sets write permissions which we
+            // already know are correct if we are writing.
+            // For efficiency, this should not be combined with the above check as flushing
+            // outputStream could change the file permissions
```
Comment (MariaSemple) [inline src/cpp/session/modules/SessionFind.cpp]: What do you mean by the above check? Does this mean flushing the output stream should happen first? Why is it for efficiency?

File: src/cpp/session/modules/SessionFind.cpp (hunk 1 above)
Comment (MariaSemple) [reply src/cpp/session/modules/SessionFind.cpp]: Could we add an update/set permissions method on FilePath to resolve this?

Comment (melissa-barca) [reply src/cpp/session/modules/SessionFind.cpp]: Maria pointed out that `FileMode` already has functions I can use so expect another update later today :)

Comment (jmcphers) [reply src/cpp/session/modules/SessionFind.cpp]: IIRC the FileMode enums do not cover all the possible permissions, so I don't think you can use them in this case.

File: src/cpp/session/modules/SessionFind.cpp (hunk 2 above)
Comment (melissa-barca) [reply src/cpp/session/modules/SessionFind.cpp]: To be honest, I'm not sure. I updated the comment to be more clear.

File: src/cpp/session/modules/SessionFind.cpp (hunk 1 above)
Comment (melissa-barca) [reply src/cpp/session/modules/SessionFind.cpp]: Ah you are correct. In that case, I'll leave the code alone and this is ready for review again.

File: src/cpp/session/modules/SessionFind.cpp [hunk 3]
```diff
@@ -487,6 +489,45 @@ class GrepOperation : public boost::enable_shared_from_this<GrepOperation>
...
+   Error getPermissions(const std::string& filePath, boost::filesystem::perms* pPerms)
+   {
+      *pPerms = boost::filesystem::no_perms;
+
+      boost::filesystem::path path(filePath);
+      try
+      {
+         boost::filesystem::file_status fileStatus = status(path);
+         *pPerms = fileStatus.permissions();
+         return Success();
```
Comment (jmcphers) [inline src/cpp/session/modules/SessionFind.cpp]: Nit: I think this return should be outside the try block for clarity (as it is in the function above)

Comment (melissa-barca) [reply src/cpp/session/modules/SessionFind.cpp]: Done!
