### PR TITLE
don't warn when failing to revert a deleted file

### LINKED ISSUE #3231: rstudio crashes on close if file no longer exists
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.846
    OS Version      : macOS 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem

Open a file in the IDE, then delete that file from the disk. You'll get a **File Deleted** prompt:

screen shot 2018-07-26 at 6 37 36 pm

Click <kbd>No</kbd>. The file remains open in the IDE, but 'dirty'. Then, attempt to quit the IDE (with <kbd>Cmd + Q</kbd>). You'll be prompted to save changes:

screen shot 2018-07-26 at 6 38 27 pm

Click <kbd>Don't Save</kbd>.

### Describe the problem in detail

A **Save File** error displays:

screen shot 2018-07-26 at 6 38 52 pm

After clicking <kbd>OK</kbd>, the session 'aborts' and the bomb is shown. (In reality, the process has already exited; the display of the dialog obscures that fact)

### Describe the behavior you expected

RStudio shouldn't crash on close.

### PR DESCRIPTION
**Pull request by kevinushey**
Closes #3231.

### CODE REVIEW

File: src/gwt/src/org/rstudio/studio/client/server/ServerErrorCause.java [hunk 1]
```diff
@@ -36,4 +36,6 @@ public String toString()
    private final int code_;
    private final String category_;
    private final String message_;
+   
+   public static final int FILE_NOT_FOUND = 2;
```
Comment (gtritchie) [inline src/gwt/src/org/rstudio/studio/client/server/ServerErrorCause.java]: Is this value platform-independent? Guessing it is, but just checking.

Comment (kevinushey) [reply src/gwt/src/org/rstudio/studio/client/server/ServerErrorCause.java]: Indeed it is, although I think it's mostly just a happy coincidence. On Unix the associated error code ENOENT (no such path or directory) maps to 2 on Linux + macOS; on Windows Boost defines its own 'file not found' error code that just so happens to equal 2 as well. (Perhaps Boost chose the Windows error codes explicitly to match the common Unix error codes?)
