### PR TITLE
Fix slow forking when ulimit for open files is high

### LINKED ISSUE #2470: RStudio can be slow when system open file ulimit is high
### System details

    RStudio Version : all
    OS Version      : Linux

### Steps to reproduce the problem

Set a very high value for the maximum number of open files, such that `ulimit -n` returns a large number (say, more than 4096). 

### Describe the problem in detail

Many operations in RStudio that spawn child processes frequently, such as performing `git` operations, become slow. 

This happens because the first thing we do in a child process is close all the file descriptors to ensure that the child can't read the parent's fds. In order to make sure that we close *all* of them, we invoke `close()` on every single descriptor up to `RLIMIT_NOFILE`.

https://github.com/rstudio/rstudio/blob/5e64c03e76e46cf5663ba307083587b4e2848e4e/src/cpp/core/system/PosixSystem.cpp#L553-L572

Individual `close()` calls are fast, but when `RLIMIT_NOFILE` is large, running thousands of them can add up, dominating the process' running time. For example, when spawning a Git process on one user's machine, it took over 0.5s to close all 4096 descriptors:

     11425 13:57:18.093725 getrlimit(RLIMIT_NOFILE, {rlim_cur=4*1024, rlim_max=4*1024}) = 0 <0.000085>
     ...
     11425 13:57:18.647213 close(4095)       = -1 EBADF (Bad file descriptor) <0.000047>

In contrast, the Git command itself only took 0.05s to run! 

Possible mitigations include:

- tracking open descriptors ourselves and manually closing only those that we know to exist, and/or
- using [`FD_CLOEXEC`](https://www.gnu.org/software/libc/manual/html_node/Descriptor-Flags.html) to keep the descriptor from surviving across the `exec` call.

### PR DESCRIPTION
**Pull request by kfeinauer**
Fixes #2470.

Now only explicitly closing the files that are open in the child process instead of attempting to close all of them up to max fd. This is accomplished in a signal-safe way by having the parent process gather the actual pids, then sending them via pipe to the child (::read is signal safe). The unsafe implementation simply fetches the fds itself instead of relying on the parent to deliver them.

### CODE REVIEW

File: src/cpp/core/system/PosixSystem.cpp [hunk 1]
```diff
@@ -533,9 +539,89 @@ Error closeFileDescriptorsFrom(int fdStart)
...
+   std::vector<FilePath> children;
+   Error error = fdDir.children(&children);
+   if (error)
+      return error;
+
+   for (const FilePath& child : children)
+   {
+      try
+      {
+         unsigned int fd = boost::lexical_cast<unsigned int>(child.filename());
```
Comment (jmcphers) [inline src/cpp/core/system/PosixSystem.cpp]: Is the reason that `safe_convert` not used here that it isn't possible to supply a default value for the conversion that isn't also a possibly valid file descriptor? (not something you need to do for this PR but wondering if we should have some convert variants that use `boost::optional` or return a bool to make it possible to write these patterns w/o explicit exception handling)

File: src/cpp/core/system/PosixSystem.cpp [hunk 2]
```diff
@@ -533,9 +539,89 @@ Error closeFileDescriptorsFrom(int fdStart)
...
+#else
+Error getOpenFds(pid_t pid, std::vector<unsigned int> *pFds)
+{
+   // get size of the buffer needed to hold the list of fds
+   int bufferSize = proc_pidinfo(pid, PROC_PIDLISTFDS, 0, 0, 0);
+   if (bufferSize == -1)
+      return systemError(errno, ERROR_LOCATION);
+
+   // get the list of open fds
+   struct proc_fdinfo* procFdInfo = (struct proc_fdinfo*)malloc(bufferSize);
```
Comment (jmcphers) [inline src/cpp/core/system/PosixSystem.cpp]: nit: prefer `static_cast` of void pointers

File: src/cpp/core/system/PosixSystem.cpp [hunk 3]
```diff
@@ -546,36 +632,107 @@ Error closeNonStdFileDescriptors()
...
+      ssize_t bytesRead = ::read(pipeFd, buffer, 4);
+
+      // check for error
+      if (bytesRead == -1 || bytesRead == 0)
+         break;
+
+      // determine which fd was just read from the parent
+      int res = (int)(*buffer);
+      if (res == -1)
+         break; // indicates no more fds are open by the process
```
Comment (jmcphers) [inline src/cpp/core/system/PosixSystem.cpp]: Does reading 0 fds from the parent indicate that we need to close every descriptor manually? (seems like we'd fall back to closing all descriptors in this case since `readDescriptors` isn't set yet)

Comment (kfeinauer) [reply src/cpp/core/system/PosixSystem.cpp]: That's correct. Reading 0 fds is an error condition, since at the minimum the std streams should be reported. The error handling condition is to basically fall back on the legacy behavior for closing all nonstd streams.

File: src/cpp/core/system/PosixSystem.cpp (hunk 2 above)
Comment (kfeinauer) [reply src/cpp/core/system/PosixSystem.cpp]: Fixed.

File: src/cpp/core/system/PosixSystem.cpp (hunk 1 above)
Comment (jmcphers) [reply src/cpp/core/system/PosixSystem.cpp]: No urgency at all but I do think it's worth investing a couple of hours in. The pattern `safe_convert::thingTo(thing, ridiculousDefault) ... if (result == ridiculousDefault) { /* handle conversion failure */ }` (which we do use) isn't great even when you *do* have a usable `ridiculousDefault`.

File: src/cpp/core/system/PosixSystem.cpp (hunk 3 above)
Comment (jmcphers) [reply src/cpp/core/system/PosixSystem.cpp]: Got it, thanks!

File: src/cpp/core/system/PosixSystem.cpp (hunk 1 above)
Comment (kfeinauer) [reply src/cpp/core/system/PosixSystem.cpp]: I will address this in a separate PR.
