### PR TITLE
Fix issues with Console handling of inverted color mode

### LINKED ISSUE #7250: Rstudio incorrectly interpretes ANSI inverse sequence
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      : Ubuntu 16.04 LTS
    R Version       :  3.6.3

### Steps to reproduce the problem

Compare the output of the following command in rstudio and in vanilla R:

cat("\033[7m\033[31mThis is visible in both \033[39mThis is visible only in the terminal\033[27m")

or, equivalently,

library(crayon)
cat(inverse(red("This is visible in both ") %+% "This is visible only in the terminal"))

In the default terminal:
First part is white on red.
Second part is white on black.

In rstudio:
First part is red on black.
Second part is black on black.

### Describe the problem in detail

If an ANSI escape sequence is within the "inverse" tags, then foreground and background should be exchanged. This happens in the default R terminal. However, in Rstudio, if a tag within the inversed text sets the foreground color, then this foreground color is not exchanged with the background.

### Describe the behavior you expected

Behavior identical to default R terminal.

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### LINKED ISSUE #7557: Console ANSI handler doesn't invert newly-set colors (256 color mode)
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.1 through latest 1.4
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem
In Console, execute this command and look at the output; repeat this exercise in R running in the Terminal pane or a standalone terminal.

The command turns on inverse mode (exchange default foreground and background) then sets a red-tone (using 256-color mode, 196 is the color) for the foreground (which should be treated as the background), then resets the foreground (hence should reset the background).

```R
cat("\033[7m\033[38;5;196mInverted with red background \033[39mInverted with default background\033[27m")
```

### Describe the problem in detail
Console output is incorrect, color-wise. 

### Describe the behavior you expected
Same behavior in Console and a terminal.

Terminal (correct):

screenshot of terminal showing correct output

Console (incorrect):

screenshot of terminal showing incorrect output

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### PR DESCRIPTION
**Pull request by gtritchie**
- Fixes #7250
- Fixes #7557 

# Fix Details
Looks like I had not completed the implementation of handling ANSI "invert" back when I added console ANSI support in RStudio 1.1.

Specifically, when invert is active, setting foreground or background colors and resetting foreground or background colors were not being inverted (e.g. setting foreground should actually set background and so on).

# QA Notes
We have pretty extensive unit testing of this code, and I wrote several new tests to cover this. To exercise it, recommend using the Crayon package and trying examples like the one in the issues themselves and/or issuing escape sequences directly.

Reference: https://en.wikipedia.org/wiki/ANSI_escape_code

### CODE REVIEW

**Comment by gtritchie** [comment]
Will fix support for 256 color mode as well before doing the PR.

File: src/gwt/src/org/rstudio/core/client/AnsiCode.java [hunk 1]
```diff
@@ -421,25 +467,45 @@ else if (codeVal == STRIKETHROUGH_OFF)
...
+               currentBgColor_.reset();
+               resetBackground();
+               clazzes_.add(INVERSE_BG_STYLE);
+            }
          }
          else if (codeVal == RESET_BACKGROUND)
          {
-            currentBgColor_.reset();
-            resetBackground();
+            if (!inverted_)
```
Comment (jmcphers) [inline src/gwt/src/org/rstudio/core/client/AnsiCode.java:498]: Totally up to you but I find these statements easier to read without the negation (i.e. `if (inverted_) { ... `)

Comment (gtritchie) [reply src/gwt/src/org/rstudio/core/client/AnsiCode.java:498]: I actually had it that way originally but I  kept misreading it (my brain was expecting the “normal” case to be first, it seemed).
