### PR TITLE
hide "Run Selection as Job" commands on Code menu when not supported

### LINKED ISSUE #5863: "Run Selection as Local (or launcher) Job" command showing inappropriately
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.2, 1.3
    OS Version      : All
    R Version       : All

### Steps to reproduce the problem
- Start the IDE
- Observe when the "Code / Run Selection as Local Job" and (on Pro) "Code / Run Selection as Launcher Job" command appears on the main menu

### Describe the problem in detail
- shows up all the time and if chosen when not appropriate will trigger a JavaScript exception due to no AppCommand handler
- closely related bug, triggers a JavaScript exception if an R file is loaded in code-browser tab (e.g. read-only R source)
- some examples of it showing when it shouldn't
    - no files open in text editor at all
    - a data viewer tab is selected in the editor region (e.g. results of `View(c(1, 2, 3))`
    - a profile results tab is selected in the editor region

### Describe the behavior you expected
- command should only be shown when an R-based file is selected in the editor region

### PR DESCRIPTION
**Pull request by gtritchie**
- Also enables running selection-as-job from code-browser tabs
- Fixes #5863

### CODE REVIEW

File: src/gwt/src/org/rstudio/studio/client/common/filetypes/TextFileType.java [hunk 1]
```diff
@@ -437,11 +437,13 @@ public String getScriptInterpreter()
...
       if (!SourceWindowManager.isMainSourceWindow())
          results.add(commands.returnDocToMain());
-      
+
       if (isR())
       {
          results.add(commands.sourceAsLauncherJob());
          results.add(commands.sourceAsJob());
+         results.add(commands.runSelectionAsJob());
+         results.add(commands.runSelectionAsLauncherJob());
```
Comment (jmcphers) [inline src/gwt/src/org/rstudio/studio/client/common/filetypes/TextFileType.java]: These commands also need to be enabled for files that can have embedded R code chunks (like R Markdown documents) -- should be a simple addition above.
