### PR TITLE
Retry open file operations when attempting to save source files / source database files

### LINKED ISSUE #7131: Constant errors when editing a file synced to Google Drive
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      : Windows 10
    R Version       : 4.0.1

### Steps to reproduce the problem
Edit a file that is saved in a folder that the Google Backup and Sync app is syncing to Google Drive.

### Describe the problem in detail
Repeatedly, you will get an error that says **The process cannot access the file because it is being used by another process**:
image

Less commonly, you'll get an error that says **The file [filename] has changed on disk. Do you want to reload the file from disk and discard your unsaved changes?**:
image

#3837 's wording or comments suggests a belief that it would fix more than just Dropbox. It does not fix this problem with Google Drive.

This is the only software I use that has so many problems with Google Drive. It is highly desirable for RStudio to be compatible with Google Drive as it provides a recovery option for data loss in cases where version control cannot help, including between check-ins/pushes or if the user does not use version control.

### Describe the behavior you expected
Editing a file in a folder synced by Google Drive creates no errors.

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### PR DESCRIPTION
**Pull request by kfeinauer**
### Intent

When dropbox or other file syncing solutions are present and attempting to sync source files that are active in the editor, save operations on said files can fail due to the inability to open the file (as it is being read in exclusive mode by the backup software).

We should attempt to retry these operations so that they do not fail often.

### Approach

This change makes it so that now we retry these operations up to a certain amount of seconds, specified by a new user preference `save_retry_timeout`, defaulting to 15. This amount of time was chosen for it to be sufficiently long to avoid nearly all exclusive locks held by backup software, while still being short enough to not seem like the operation is stalled.

Instead of doing a retry on all file operations via modifying of the `FilePath` class, I scoped this down to only target the helper `writeStringToFile`, and its invocations in the source database. This is to reduce impact and risk of inadvertently slowing down some other processes in other parts of the code base that might not expect it. 

Closes #7131 

### QA Notes

See repro steps in #7131. The user pref `save_retry_timeout` can be lowered to increase the likelihood of reproducing the original issue.

### CODE REVIEW

File: src/cpp/core/FileSerializer.cpp [hunk 1]
```diff
@@ -24,13 +24,63 @@
...
+   bool opened = false;
+   ptime startTime = second_clock::universal_time();
+   Error lastError;
+
+   // do not allow negative values - regular signed int was chosen here for
+   // easier integration with other parts of the codebase
+   if (maxOpenRetrySeconds < 0)
+      maxOpenRetrySeconds = 0;
+
+   while (!opened)
```
Comment (kevinushey) [inline src/cpp/core/FileSerializer.cpp:63]: It looks like this loop doesn't update `opened` below?

Comment (kfeinauer) [reply src/cpp/core/FileSerializer.cpp]: Thanks for that - this was some leftovers from my prior impl that was using `do{}while();`. Changed this to just be a `while(true)` since it either exits the loop via return or a break when the time has elapsed.

File: src/cpp/core/FileSerializer.cpp [hunk 2]
```diff
@@ -24,13 +24,62 @@
...
+      // if the error is a non file lock error, then we should just return it
+      if (!isFileLockedError(lastError))
+         return lastError;
+
+      // stop retrying if we've spent more than the requested amount of time
+      if ((second_clock::universal_time() - startTime) >= seconds(maxOpenRetrySeconds))
+         break;
+
+      // wait a moment before retrying
+      boost::this_thread::sleep(milliseconds(500));
```
Comment (jmcphers) [inline src/cpp/core/FileSerializer.cpp:75]: Does this actually pause the whole RPC thread? I'm a little concerned that if (a) we auto backup changes every 500ms (the default), and (b) every (other) attempt to write backups pauses the RPC thread for 500+ms as we wait for GDrive (etc) to release the lock, the RPC thread is going to spend a pathologically large time locked.

Comment (kfeinauer) [reply src/cpp/core/FileSerializer.cpp:75]: It does since it is sleeping. I did my testing with auto save on 500 ms and the performance seemed good. The vast majority of saves are non conflicting - I'd say one in every 15-20 saves produced a stall waiting for the file to become available in my testing. I didn't notice any ill effects from a UX perspective.

This also reduces a bunch of complexity as opposed to retrying the operations in the front end and having to re-queue operations.

**Comment by kevinushey** [comment]
One worry I have: what if another application locks something in the source database, and for whatever reason refuses to release that lock? It feels like in that case the user could get stuck -- e.g. what if they start mashing the save button (queueing up new save RPC requests) and each of those takes 15 seconds to eventually fail to save and otherwise locks up the IDE for that duration.

File: src/cpp/core/FileSerializer.cpp (hunk 2 above)
Comment (jmcphers) [reply src/cpp/core/FileSerializer.cpp:75]: Was your testing on a system with a fast SSD and internet connection? I think that GDrive and friends can have an exclusive lock for much longer on some environments, leading to more save conflicts. 

I think we need to give up faster on autosaves. The user generally has another chance to save the file (and will get warned if they try to exit with changes that have never been backed up); it feels wrong that there's a possibility of blocking the entire RPC thread for 15 seconds for an operation the user didn't initiate. 

15s isn't unreasonable for a change that must succeed, so I'd suggest a second pref for autosave (auto_save_retry_timeout?) as both a shorter fuse and an escape hatch; it could give up after a second or two, and setting it to 0 would result in a best-effort autosave that just attempts to write the file if it can (the front end could read this value and avoid popping up "file is in use" errors).

Comment (kfeinauer) [reply src/cpp/core/FileSerializer.cpp:75]: What about not retrying for autosaves period? The whole point of autosaves is that it saves continuously and periodically. Since most operations are successful, we could simply ignore this particular failure for autosaves entirely, with the knowledge that future autosaves will almost assuredly work (since the exclusive file lock will be given up as soon as syncing is done).

We can keep everything as is currently for manual saves, since they are a user initiated action.

**Comment by kfeinauer** [comment]
@kevinushey I think what we have is reasonable for manual saves because it's a user initiated action, and it's certainly not a common occurrence for these files to be permanently locked by some other application. 

I do agree that we should only allow one pending save operation in flight at any given time though. Is this something we are already preventing?

**Comment by kfeinauer** [comment]
@jmcphers This is ready for another review.

These changes continue with the philosophy that autosave transient failures should not produce a user dismissible error - these errors should only show for user initiated actions.

Made the following changes:

1. Only attempt a retry operation if it was the result of a manual user operation - autosaves will now no longer stall the pipeline by continuously retrying
2. Hide the autosave failure if it is due to transient file lock
3. Fix issue where lastKnownWriteTime could get out of sync if the file data is written but its source database metadata is not - this was directly observable in the original bug report
4. Restart the autosave operation if it failed silently

File: src/cpp/core/include/core/FileSerializer.hpp [hunk 3]
```diff
@@ -291,10 +291,16 @@ Error readStringVectorFromFile(const core::FilePath& filePath,
                                bool trimAndIgnoreBlankLines=true);
 
 // lineEnding is the type of line ending you want to end up on disk
+//
+// maxOpenRetrySeconds indicates whether or not we should retry attempts to open the file
+// when it is in use by another process (common when using backup software), and if so
+// how many seconds of elapsed time should we wait for the file to become available
+// note: this only has an affect on Windows
```
Comment (jmcphers) [inline src/cpp/core/include/core/FileSerializer.hpp:298]:
```suggestion
// note: this only has an effect on Windows
```

File: src/cpp/session/SessionSourceDatabase.cpp [hunk 4]
```diff
@@ -71,13 +74,30 @@ namespace {
 // lookup)
 std::map<std::string, std::string> s_idToPath;
 
+// cached mapping of document last write times
+std::map<std::string, std::time_t> s_lastWriteTimes;
```
Comment (jmcphers) [inline src/cpp/session/SessionSourceDatabase.cpp:78]: Does this need to be a threadsafe map?

File: src/cpp/core/FileSerializer.cpp [hunk 5]
```diff
@@ -24,13 +24,62 @@
...
+   {
+      lastError = filePath.openForWrite(*pOfs, truncate);
+
+      // if the error is a non file lock error, then we should just return it
+      if (!isFileLockedError(lastError))
+         return lastError;
+
+      // stop retrying if we've spent more than the requested amount of time
+      if ((second_clock::universal_time() - startTime) >= seconds(maxOpenRetrySeconds))
+         break;
```
Comment (jmcphers) [inline src/cpp/core/FileSerializer.cpp:72]: Can we amend the primary error object here with a property that indicates that we timed out (and possibly how many tries/attempts we made)? I also think this error would be worth logging _and_ returning since a save failure can cause data loss.

**Review by jmcphers — CHANGES_REQUESTED** [review]

File: src/cpp/session/SessionSourceDatabase.cpp (hunk 4 above)
Comment (kfeinauer) [reply src/cpp/session/SessionSourceDatabase.cpp:78]: No - all of these routines execute only on the main thread (thread 0)

**Comment by kfeinauer** [comment]
@jmcphers @kevinushey Updated

File: src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java [hunk 6]
```diff
@@ -376,8 +391,17 @@ public void onError(final String message)
             @Override
             public void execute()
             {
-               globalDisplay_.showErrorMessage("Error Saving File",
-                                               message);
+               // do not show the error if it is a transient autosave related issue - this can occur fairly frequently
+               // when attempting to save files that are being backed up by external software
+               if (message.contains("The process cannot access the file because it is being used by another process") && suppressFileLockError_)
```
Comment (kevinushey) [inline src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java:396]: Checking this based on the message rather than an error property or code seems fragile. Would it be feasible for us to send a proper error object (e.g. with an error code) that we could check here or something similar?

File: src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java [hunk 7]
```diff
@@ -7708,7 +7760,7 @@ public void setPath(FileSystemItem path)
       TextFileType type = fileTypeRegistry_.getTextTypeForFile(path);
 
       // Simulate a completed save of the new path
-      new SaveProgressIndicator(path, type, null).onCompleted();
+      new SaveProgressIndicator(path, type, false,null).onCompleted();
```
Comment (kevinushey) [inline src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java:7763]:
```suggestion
      new SaveProgressIndicator(path, type, false, null).onCompleted();
```

File: src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java (hunk 6 above)
Comment (kfeinauer) [reply src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java:396]: I decided against that because we are using the `ProgressIndicator` interface here which is tied to error messages and is a very fundamental interface in the code. I didn't think extending this interface was worth it to propagate this one error code here as this would affect a very large portion of the code base.

**Review by jmcphers — APPROVED** [review]
LGTM, let's definitely add a NEWS entry for this one!
