### PR TITLE
Fix issues with Cmd+W on macOS

### LINKED ISSUE #2301: focus/keyboard input issues in preview window
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.375
    OS Version      : macOS 10.13.3
    R Version       : 3.4.3

### Steps to reproduce the problem

Given the R Markdown document:
````
---
output: revealjs::revealjs_presentation
---

## First!

here is the first slide

## Aww. Second.

this is not the first slide
````

Knit the document (with Command-Shift-K) and have it open in a preview window.

Knit settings:
screen shot 2018-03-02 at 9 12 52 am

### Describe the problem in detail

The resulting preview window initially does not respond to arrow events (left, right). If you click in the window to give it focus, it then responds to left/right events.

The preview window does not respond to Command-W events even after click-to-focus.

### Describe the behavior you expected

* The preview window responds to left/right events immediately after opening (it does not require click-to-focus).
* The preview window is always closed by Command-W.

```
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
 [1] compiler_3.4.3  backports_1.1.2 magrittr_1.5    rsconnect_0.8.7
 [5] rprojroot_1.3-2 htmltools_0.3.6 tools_3.4.3     revealjs_0.9   
 [9] yaml_2.1.16     Rcpp_0.12.14    stringi_1.1.6   rmarkdown_1.9  
[13] knitr_1.20      stringr_1.2.0   digest_0.6.15   evaluate_0.10.1
```

### PR DESCRIPTION
**Pull request by jmcphers**
On macOS, Cmd+W is overloaded. In the main window and source windows, it closes source documents. In other windows, *and* in the main window/source window when no docs are open, it closes the whole window.

This has been broken since the QtWebEngine transition. Fixing it turned out to involve solving three problems.

### keyEvent handlers not called

Because our `WebView::event` override delegates directly to `QtWebEngineView`, our `keyEvent` handler never gets called. Now, we check for an override event, and on macOS we take the opportunity to implement our own Qt key handling.

### isDesktop is not reliable during GWT startup

We use `isDesktop()` all over the place, but it relies on `window.desktop` being present. In QtWebEngine, that object is now injected asynchronously and may not be available during GWT startup. Consequently, some code that runs on startup thinks that it's in server mode. 

In other words, `isDesktop` conflates two different questions: "am I in desktop mode?" and "can I talk to the WebChannel"? These are now two different functions: `isDesktop` checks for a new static variable that is available synchronously, and `isDesktopReady` checks for the asynchronously available WebChannel.

### Source window is closed on Cmd + W

Source Windows are satellites, and they closed without condition `onCloseWindowShortcut()`. This meant that you couldn't close individual documents in a source window with Cmd + W (it just closed the whole window). 

The code which checks `onCloseSourceDoc` has been moved back to `GwtWindow`, so it's shared among the source and main windows (and several others which don't need it, so it's been tweaked slightly so the window itself can tell us whether it needs the check). 

Fixes #2301.

### CODE REVIEW

File: src/cpp/desktop/DesktopGwtWindow.cpp [hunk 1]
```diff
@@ -118,6 +118,22 @@ bool GwtWindow::event(QEvent* pEvent)
    return BrowserWindow::event(pEvent);
 }
 
+void GwtWindow::onCloseWindowShortcut()
+{
+   // check to see if the window has desktop hooks (not all GWT windows do); if it does, check to
+   // see whether it has a closeSourceDoc() command we should be executing instead
+   webPage()->runJavaScript(
+            QStringLiteral(
+               "if (window.desktopHooks) "
```
Comment (kevinushey) [inline src/cpp/desktop/DesktopGwtWindow.cpp]: Worth noting that writing this kind of inline code is a lot nicer with C++11 raw string literals

File: src/cpp/desktop/DesktopWebView.cpp [hunk 2]
```diff
@@ -132,6 +148,14 @@ qreal WebView::dpiAwareZoomFactor()
 
 bool WebView::event(QEvent* event)
 {
+   if (event->type() == QEvent::ShortcutOverride)
+   {
+      // take a first crack at shortcuts
+      QKeyEvent *pKeyEvent = dynamic_cast<QKeyEvent*>(event);
```
Comment (kevinushey) [inline src/cpp/desktop/DesktopWebView.cpp]: I think you can safely use `static_cast` rather than `dynamic_cast` here.

Comment (jmcphers) [reply src/cpp/desktop/DesktopWebView.cpp]: You're right, this is probably overly pessimistic (Qt uses `static_cast` in their [own example](https://wiki.qt.io/ShortcutOverride)). I'll make the change.
