### PR TITLE
remove specialized scrollbars from Packages pane

### LINKED ISSUE #3085: "Remove package" icons are mostly obscured by scrollbar
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.2.780
    OS Version      : Desktop: MacOS 10.12.6 (Sierra), Windows 10, Linux (Ubuntu 18.04); Server: MacOS/Chrome to Red Hat 7.5
    R Version       : 3.4.4 & 3.5.0

### Steps to reproduce the problem

Choose Packages pane.

### Describe the problem in detail

The "remove package" icons on the right are mostly obscured by the scrollbar. They can only be clicked by moving the cursor to a tiny area on the left.

### Describe the behavior you expected

The "remove package" icons should be completely visible.

This was not an issue in 1.1.453 in which only "remove package" icons were present. In 1.2, though, there is also a "browse package" icon and a nefarious scrollbar.

### PR DESCRIPTION
**Pull request by kevinushey**
GWT's DataGrid class attempts to draw its own specialized scrollbars, by placing an absolutely-positioned div of appropriate height with a slight blur to make the scrollbar transparent. Unfortunately, as a side effect of how GWT draws the scrollbar, it's possible to obscure the actual content in the associated table. This is especially an issue as in #3085 the scrollbar can effectively obscure buttons that we attempt to draw in the table.

The fix here is to delete the specialized GWT scrollbar element, and allow the browser to draw the scrollbar as appropriate. This also allows the browser to resize the table according to whether an overlay scrollbar is drawn, versus a regular space-occupying scrollbar.

Closes #3085.

### CODE REVIEW

File: src/gwt/src/org/rstudio/studio/client/workbench/views/packages/PackagesPane.java [hunk 1]
```diff
@@ -473,6 +488,35 @@ else if (source == "source")
...
+         // scrollbars.
+         Element.as(children.getItem(1)).getStyle().clearPosition();
+         Element.as(children.getItem(1).getChild(0)).getStyle().setOverflow(Overflow.AUTO);
+         
+         // Remove the div containing the custom GWT scroller.
+         el.removeChild(children.getItem(children.getLength() - 1));
+      }
+      catch (Exception e)
+      {
+         Debug.logException(e);;
```
Comment (jmcphers) [inline src/gwt/src/org/rstudio/studio/client/workbench/views/packages/PackagesPane.java]: Nit: double semicolon

File: src/gwt/src/org/rstudio/studio/client/workbench/views/packages/PackagesPane.java [hunk 2]
```diff
@@ -344,6 +350,15 @@ public void run()
    
    private void initPackagesTable()
    {
+      Scheduler.get().scheduleDeferred(new ScheduledCommand()
+      {
+         @Override
+         public void execute()
+         {
+            onPackagesTableReady();
```
Comment (jmcphers) [inline src/gwt/src/org/rstudio/studio/client/workbench/views/packages/PackagesPane.java]: Should this be done in `onAttach`? I'm not sure there's a guarantee of a live DOM here (although if it appears to work reliably that's probably good enough!)

**Comment by jmcphers** [comment]
One other question: is there a reason we shouldn't just do this for all DataGrids? As part of a recent change I created an `RStudioDataGrid` which does very similar surgery so wondering if we should move this fixup and then have the Packages pane use `RStudioDataGrid`.

**Comment by jmcphers** [comment]
Hah, just wrote that before seeing you'd made a comment to the same effect. Great minds think alike!

**Comment by kevinushey** [comment]
I just realized why GWT does this dance with the scrollbars -- it's to ensure alignment works as expected with the column headers. Since the scrollbar is drawn only within the table body, if it also takes up space in the layout, it causes the columns to become misaligned with the header. Dang.

I'll investigate a bit more to see if we can discover a better fix...

**Comment by kevinushey** [comment]
Okay, I think we have an appropriate fix here. We compute the width of scrollbars in the current browser, and use that to add some extra padding as needed to the final column in the Packages pane's Data Grid.

Note that this needs to be a case-by-case fix as this only works for columns that enforce a width for the rightmost column, rather than allowing the right-most column to have a variable width.
