### PR TITLE
Fix issue with zoom column commands

### LINKED ISSUE #7687: Additional source column and zoom not working
### System details

    RStudio Edition :Both
    RStudio Version : 1.4.752
    OS Version      : MacOS
    R Version       : 3.6

### Steps to reproduce the problem
1. Add an additional source column (view -> panes -> add source column)
2. Then attempt to zoom in on a different pane (view-> panes -> zoom Files)

### Describe the problem in detail
zooms into the pane but user cannot interact with the pane. Also not everything is displayed in the zoomed in pane and theres no horizontal scrollbar

Screen Shot 2020-08-31 at 12 22 30 PM

### Describe the behavior you expected
Pane is zoomed in fully and user can interact with the pane

- [ ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [ ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### PR DESCRIPTION
**Pull request by melissa-barca**
### Intent

Fixes #7687 

The main purpose of this PR is to fix an issue affecting the `Zoom Left Column` and `Zoom Right Column` commands when user has additional source columns open. The issue is primarily caused by the fact that the "left column" is no longer the left column with additional source columns. 
This also fixes and issue where`WindowEnsureVisibleEvent` was never updated to handle multiple source windows but was being initiated by source columns.

### Approach

This PR only ensure both commands work as they used to (zooming on the right column or left/center column). Another one will need to be created to have the wording of the commands updated and commands to zoom on the additional source columns.

The majority of the new logic is to ensure clean animation when transitioning to/from a zoomed state. Existing logic was only for the right side which always has one panel. For the left side, I need to calculate the total size to be displayed and then allocate those pixels so that they loaded left -> right or right -> left.

### QA Notes

These issues only happen when using additional source columns. We should make sure different orderings of the zoom commands work as they did in 1.3.

### CODE REVIEW

File: src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java [hunk 1]
```diff
@@ -577,10 +590,12 @@ public void onLayoutConsoleOnRight()
       }
    }
 
+   // The following commands need to be updated to fit the new layout with additional source 
+   // columns. The mismatched names/actions are temporarily intentional until this is handled.
```
Comment (jmcphers) [inline src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java:594]: Do we have an issue open on this?

File: src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java [hunk 2]
```diff
@@ -946,7 +1106,26 @@ private void restoreSavedLayout()
...
+            leftStart.add(0.0);
+
+         if (leftWidgetSizePriorToZoom_.size() != leftList_.size())
+            leftEnd = getValidColumnWidths(leftList_, leftWidgetSizePriorToZoom_, false);
+         else
+         {
+            // Copy leftWidgetSizePriorToZoom_ rather than passing it directly because it may be
+            // cleared before animation completes
+            for (Double size : leftWidgetSizePriorToZoom_)
+               leftEnd.add(size);
```
Comment (jmcphers) [inline src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java:1124]: Nit: `addAll` will do this in one line

**Review by jmcphers — APPROVED** [review]

File: src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java (hunk 1 above)
Comment (melissa-barca) [reply src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java:594]: I've created one here: #7801

File: src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java (hunk 2 above)
Comment (melissa-barca) [reply src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java:1124]: Doesn't `addAll` only do a shallow copy though?

Comment (gtritchie) [reply src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java:1124]: IntelliJ also recommends replacing with `addAll`.

**Review by gtritchie — APPROVED** [review]
LGTM!

File: src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java (hunk 2 above)
Comment (jmcphers) [reply src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java:1124]: It does do a shallow copy, but this loop also does a shallow copy.

Comment (melissa-barca) [reply src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java:1124]: You're right, but I think it's ok because this gets passed as a final parameter. I've updated to follow your nit.
