### PR TITLE
correctly detect and handle attempts to load iframes

### LINKED ISSUE #2756: IFrames with external URLs pop up in separate windows
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.616
    OS Version      : macOS 10.13

### Steps to reproduce the problem

Run these two commands:

    > library(htmltools)
    > print(browse = TRUE, tags$iframe(src="https://www.rstudio.com/"))

### Describe the problem in detail

The `iframe` displays in the Viewer pane, but it's empty, and the RStudio.com website opens in a new browser window.

### Describe the behavior you expected

No external windows should be opened.

This regression occurred because QtWebEngine does not tell us what kind of `NavigationType` is being requested; we cannot distinguish between link clicks (which should indeed open external windows) and IFrame loads (which should not). 

https://github.com/rstudio/rstudio/blob/71ff50d204963610b4c338f912600e44d0ca3c0d/src/cpp/desktop/DesktopWebPage.cpp#L244-L252

We will need to distinguish between these cases in some other way.

### PR DESCRIPTION
**Pull request by kevinushey**
This PR ensures that `iframe`s requested in the main window are loaded in RStudio, rather than a separate browser window.

Closes #2756.

### CODE REVIEW

File: src/cpp/desktop/DesktopWebPage.cpp [hunk 1]
```diff
@@ -286,6 +286,11 @@ bool WebPage::acceptNavigationRequest(const QUrl &url,
    {
       return true;
    }
+   // allow iframes
+   else if (desktop::urlRequestInfoResourceType() == QWebEngineUrlRequestInfo::ResourceTypeSubFrame)
```
Comment (jmcphers) [inline src/cpp/desktop/DesktopWebPage.cpp]: If we're going to universally allow subframes to load, then we can dispense with almost every one of the above cases, because viewer URLs, Shiny apps, etc. are always loaded in subframes (even in dedicated windows they use an iframe wrapped in a GWT widget)

File: src/cpp/desktop/DesktopWebProfile.cpp [hunk 2]
```diff
@@ -24,6 +24,8 @@ namespace desktop {
 
 namespace {
 
+QWebEngineUrlRequestInfo::ResourceType s_urlRequestInfoResourceType;
```
Comment (jmcphers) [inline src/cpp/desktop/DesktopWebProfile.cpp]: Should this be a static? (can't recall if we have a single WebProfile instance but IIRC there's one per window so each would need its own copy of this)

Comment (kevinushey) [reply src/cpp/desktop/DesktopWebProfile.cpp]: Good point; each WebPage gets their own WebProfile so this should likely be a member variable. I'll fix that up.

File: src/cpp/desktop/DesktopWebPage.cpp (hunk 1 above)
Comment (kevinushey) [reply src/cpp/desktop/DesktopWebPage.cpp]: Do you think this is reasonable now that we can sandbox our iframes?

Comment (jmcphers) [reply src/cpp/desktop/DesktopWebPage.cpp]: We can sandbox iframes, and we do sandbox the viewer pane when it's showing an external URL. 

https://github.com/rstudio/rstudio/blob/fc4cb83997bee8dda33cfaf4060dfaf0107f0ba7/src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/ViewerPane.java#L263-L277

However this is largely irrelevant for this discussion as it's a fool's errand to try to guarantee that the `sandbox` attribute gets injected into every iframe RStudio ever loads. If we take this change we're basically putting our trust in QtWebEngine's cross domain security policy to keep us protected from whatever the wild internet throws at us.

Comment (kevinushey) [reply src/cpp/desktop/DesktopWebPage.cpp]: Got it (sorry for being a bit dense). I've updated this PR to ensure that we _don't_ load subframes (other than our own whitelisted set) and if we ever want to open the floodgates (so to speak) we can discuss that in a separate PR.

Comment (jmcphers) [reply src/cpp/desktop/DesktopWebPage.cpp]: Sounds good!
