### PR TITLE
fixups for setting desktop zoom level

### LINKED ISSUE #3277: adjusting zoom level in Global Options pane doesn't work
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.877
    OS Version      : Ubuntu 18.04 64bit (GNOME 3)
    R Version       : 3.5.1

### Steps to reproduce the problem

Tools -> Global Options... -> Appearance -> Zoom. Try changing the zoom level, and then hitting apply.

### Describe the problem in detail

The old zoom level is used.

### Describe the behavior you expected

The new zoom level should be used.

Note that the new zoom level is properly persisted at `~/.config/RStudio/desktop.ini` so it appears that we're caching and reusing an old zoom value.

### PR DESCRIPTION
**Pull request by kevinushey**
Closes #3277.

### CODE REVIEW

File: src/cpp/desktop/DesktopGwtCallback.cpp [hunk 1]
```diff
@@ -1274,8 +1274,7 @@ double GwtCallback::getZoomLevel()
 
 void GwtCallback::setZoomLevel(double zoomLevel)
 {
-   options().setZoomLevel(zoomLevel);
-   desktopInfo().setZoomLevel(zoomLevel);
```
Comment (kevinushey) [inline src/cpp/desktop/DesktopGwtCallback.cpp]: Note that this was redundant (setting the preference in options also updates the desktopInfo instance) so it's been removed.

File: src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java [hunk 2]
```diff
@@ -426,19 +426,22 @@ public boolean onApply(RPrefs rPrefs)
...
+            Desktop.getFrame().setFixedWidthFont(fontFace);
             restartRequired = true;
          }
          
          if (!StringUtil.equals(initialZoomLevel_, zoomLevel_.getValue()))
          {
             double zoomLevel = Double.parseDouble(zoomLevel_.getValue());
+            initialZoomLevel_ = zoomLevel_.getValue();
             Desktop.getFrame().setZoomLevel(zoomLevel);
-            restartRequired = true;
```
Comment (kevinushey) [inline src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java]: Restart is indeed no longer required when setting the zoom level with WebEngine (hurray!)

File: src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java [hunk 3]
```diff
@@ -426,19 +426,22 @@ public boolean onApply(RPrefs rPrefs)
...
+            String fontFace = fontFace_.getValue();
+            initialFontFace_ = fontFace;
+            Desktop.getFrame().setFixedWidthFont(fontFace);
             restartRequired = true;
          }
          
          if (!StringUtil.equals(initialZoomLevel_, zoomLevel_.getValue()))
          {
             double zoomLevel = Double.parseDouble(zoomLevel_.getValue());
+            initialZoomLevel_ = zoomLevel_.getValue();
```
Comment (kevinushey) [inline src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java]: Note that updating this is necessary as otherwise changing to a zoom level but then attempting to revert to the previous setting would fail (as the UI would interpret this as no change)
