### PR TITLE
AppleScript support

### LINKED ISSUE #3354: RStudio no longer supports AppleScript
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.907
    OS Version      : 10.13.4
    R Version       : 3.5.1

### Steps to reproduce the problem

The applescript no longer works
```
tell application "RStudio"
    cmd "a=1"
end tell
```

### Describe the problem in detail

In https://github.com/rstudio/rstudio/pull/527, I have submitted a PR to add support of AppleScript. It was applied to the mac specific app in `desktop-mac`. In RStudio 1.2, it seems that the development has moved back to the cross-platform code located in `desktop`. However, the code related of AppleScript was not migrated to the `desktop` app.

### PR DESCRIPTION
**Pull request by randy3k**
Not the most beautiful way to do it, but it works.

close #3354

### CODE REVIEW

File: src/cpp/desktop/DesktopMainWindow.hpp [hunk 1]
```diff
@@ -40,7 +40,11 @@ class MainWindow : public GwtWindow
 public:
    explicit MainWindow(QUrl url=QUrl());
 
+private:
+   static MainWindow *instance;
+
 public:
+   static MainWindow *getInstance();
```
Comment (kevinushey) [inline src/cpp/desktop/DesktopMainWindow.hpp]: I'm not a fan of this. Why not have `ScriptCommand.mm` accept a `MainWindow` as part of its constructor? Or if that's not possible for some reason, have a method that it can call to 'bind' to a window instance.

File: src/cpp/desktop/ScriptCommand.h [hunk 2]
```diff
@@ -0,0 +1,22 @@
+/*
+ * ScriptCommand.h
+ *
+ * Copyright (C) 2009-17 by RStudio, Inc.
```
Comment (kevinushey) [inline src/cpp/desktop/ScriptCommand.h]: nit: 2009-18

File: src/cpp/desktop/ScriptCommand.mm [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+ *
+ */
+
+#import <Foundation/Foundation.h>
+#import "ScriptCommand.h"
+#include "DesktopMainWindow.hpp"
+#include <boost/algorithm/string/replace.hpp>
+
+
+std::string jsEscape(std::string str)
```
Comment (kevinushey) [inline src/cpp/desktop/ScriptCommand.mm]: We have a couple escape helpers here: do any of them suffice?

https://github.com/rstudio/rstudio/blob/f5ba8af725c845a1097277ad3f812103b8ab090f/src/cpp/core/include/core/StringUtils.hpp#L91-L95

File: src/cpp/desktop/ScriptCommand.mm [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+   return str;
+}
+
+
+// evaluate R command
+void evaluateRCommand(std::string rCmd)
+{
+   rCmd = jsEscape(rCmd);
+   std::string js = "window.desktopHooks.evaluateRCmd(\"" + rCmd + "\")";
+   rstudio::desktop::MainWindow::getInstance()->webPage()->runJavaScript(QString::fromUtf8(js.c_str()));
```
Comment (kevinushey) [inline src/cpp/desktop/ScriptCommand.mm]: nit: there is a `QString::fromStdString()` method that you might consider using here

File: src/cpp/desktop/DesktopMainWindow.hpp (hunk 1 above)
Comment (randy3k) [reply src/cpp/desktop/DesktopMainWindow.hpp]: I am not sure if it is possible to dynamically initialize `NSScriptCommand`, akaik, it is usually initialized automatically by the application. This implementation just mirrors `desktop-mac`'s: https://github.com/rstudio/rstudio/blob/54caf1f66b724680091623b6eca157870e3a3e6c/src/cpp/desktop-mac/MainFrameController.mm#L37

Comment (kevinushey) [reply src/cpp/desktop/DesktopMainWindow.hpp]: Perhaps the `evaluateRScriptCommand` class could gain a function e.g. `- initialize(MainWindow* window)` that gets called by the `MainWindow` class when appropriate? And that could take care of setting the `MainWindow` instance so that it can be used.

**Comment by kevinushey** [comment]
Great!

Just to double-check: does this work as expected when there are multiple RStudio windows open (e.g. if you have multiple main windows; perhaps with different projects open)?

**Comment by randy3k** [comment]
it will always send to the newest instance. In order to support multiple instances, we will need communications between the sessions. I may be able to work on it in the future if you could point me to the correct files to look at.

**Comment by kevinushey** [comment]
I think it's okay if we just send to the newest RStudio instance. You might even want to set things up so that commands are sent to the most recently focused RStudio window.

**Comment by randy3k** [comment]
>I think it's okay if we just send to the newest RStudio instance. You might even want to set things up so that commands are sent to the most recently focused RStudio window.

@kevinushey unfortunately it is not possible without a session manager. Ideally, there should be only one instance and a new session is opened in the same instance, like how Safari works.

**Comment by randy3k** [comment]
@kevinushey I hope the RStudio team would consider merging this into v1.2 release as AppleScript was already supported v1.1.

**Comment by kevinushey** [comment]
Yes, we will take this for v1.2. Thanks again for the PR!

**Comment by randy3k** [comment]
Awesome.
