### PR TITLE
Fix issue with global replace

### LINKED ISSUE #6819: Global find and replace fails
### System details

    RStudio Edition : Desktop or Server 
    RStudio Version : 1.3.957-1
    OS Version      : Windows 10
    R Version       : 4.0.0

### Steps to reproduce the problem

1) Create a new RStudio project that contains documents with non-English letters e.g., text
```
Apie atsitiktinę ir sistemingąją imties (pa)klaidas rašoma [@Cekanavicius2006, p.14-15, sk. 2.3].
```
You may use this project:
[replacement-issue.zip](https://github.com/rstudio/rstudio/files/4588589/replacement-issue.zip)

I will demonstrate by using my original project.

2) Press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd> in order to replace from `Cekanavicius2006` to `Cekanavicius_stat_I`. Next, follow the print-sceen instructions.

3)
image

4)
image

5)
image

6)
image

7)
image

Screenshots from GitHub Desktop for Windows:
image
image
image

It seems that the issue might be related to non-English characters, that preceded the text to replace. In places with correct replacement, there were no non-English letters.

image

### Describe the problem in detail

Global Find and Replace is not reliable: it fails to replace correctly. It is dangerous as using it without version control may result in damaged documents.

### Describe the behavior you expected

Replacement must work correctly.

### PR DESCRIPTION
**Pull request by melissa-barca**
Fixes #6819

This PR updates the global find and replace code to be fully functional across different encodings and adds additional tests so that this issue will not repeat itself (I plan on adding more but want to get this looked at for 1.3). Replaces in certain languages were only working as regular expression replaces and even then the green highlight wasn't displaying properly. They can now be performed as literal replaces across encodings already supported by RStudio, and the highlights will properly match the outcome.

I coded this against v1.3-patch so want to merge there first, but believe this should also go into v1.3.

### CODE REVIEW

File: src/cpp/session/modules/SessionFind.cpp [hunk 1]
```diff
@@ -780,55 +799,81 @@ class GrepOperation : public boost::enable_shared_from_this<GrepOperation>
...
+               }
+
+               // If we found a different number of matches searching the encoded string,
+               // we shouldn't perform the replace as the expected vs actual results may differ.
+               if (!encoding_.empty() && eMatchOnArray.getSize() != matchOnArray.getSize())
+               {
+                  core::Error error(
+                     errc::findCategory(),
+                     errc::RegexError,
+                     "Could not perform replace due to encoding issue.",
```
Comment (jmcphers) [inline src/cpp/session/modules/SessionFind.cpp:819]: Could this be made more specific so that we have more to go on if it's seen in the wild? E.g.:

"Found X matches in line but Y matches in encoded line; skipping replace."

File: src/cpp/session/modules/SessionFind.cpp [hunk 2]
```diff
@@ -1643,24 +1752,25 @@ core::Error Replacer::completeReplace(const boost::regex& searchRegex,
...
-   std::string endOfString = pLine->substr(matchOff).c_str();
-   size_t replaceMatchOff;
-   if (endOfString.empty())
-      replaceMatchOff = temp.length();
-   else
-      replaceMatchOff = temp.find(endOfString);
+   newLine.insert(0, begin);
+   *pReplaceMatchOff = newLine.length() - end.length();
+   *pLine = newLine;
+/*
```
Comment (jmcphers) [inline src/cpp/session/modules/SessionFind.cpp:1758]: Do we need this commented code? (feels like it should just be removed)

File: src/cpp/session/modules/SessionFind.cpp (hunk 1 above)
Comment (melissa-barca) [reply src/cpp/session/modules/SessionFind.cpp]: Good idea, fixed.

File: src/cpp/session/modules/SessionFind.cpp (hunk 2 above)
Comment (melissa-barca) [reply src/cpp/session/modules/SessionFind.cpp]: You're right, just me making sure I had the right math. I've removed it.

File: src/cpp/session/modules/SessionFind.cpp [hunk 3]
```diff
@@ -741,6 +719,38 @@ class GrepOperation : public boost::enable_shared_from_this<GrepOperation>
...
+      while (regex_utils::search(inputPos, match, getColorEncodingRegex(findResults().gitFlag())))
+      {
+         std::string matchedString(inputPos, inputPos + match.position());
+         inputPos += match.position() + match.length();
+         
+         cleanLine.append(matchedString);
+
+         charactersProcessed += matchedString.size();
+   
+         if ((match.size() > 2 && match[2] == "1" && findResults().gitFlag()) ||
```
Comment (MariaSemple) [inline src/cpp/session/modules/SessionFind.cpp:743]: I think these string literals should have a comment explaining what they mean/where they come from.

File: src/cpp/session/modules/SessionFind.cpp [hunk 4]
```diff
@@ -741,6 +719,38 @@ class GrepOperation : public boost::enable_shared_from_this<GrepOperation>
       return error;
    }
 
+   void cleanLineAndGetMatches(std::string* pEncodedLine,
+                               json::Array* pMatchOn, json::Array* pMatchOff)
+   {
+      // The incoming string is assumed to have color encodings from the initial grep command.
+      // These encodings are parsed out and their positions are placed in pMatchOn and pMatchOff.
```
Comment (MariaSemple) [inline src/cpp/session/modules/SessionFind.cpp:726]: Why do we put them into `pMatchOn` and `pMatchOff`? Are we removing the color encodings or just keeping track of them?

File: src/cpp/session/modules/SessionFind.cpp [hunk 5]
```diff
@@ -1620,15 +1669,75 @@ boost::regex getColorEncodingRegex(bool isGitGrep)
...
 
+
+Error Replacer::replacePreview(const size_t dMatchOn, const size_t dMatchOff,
+                               size_t eMatchOn, size_t eMatchOff,
+                               std::string* pEncodedLine, std::string* pDecodedLine,
+                               size_t* pReplaceMatchOff) const
+{
+   // if we're not encoded, we can avoid some logic
+   bool encoded = true;
+   if (eMatchOn == 0 && eMatchOff == 0)
```
Comment (MariaSemple) [inline src/cpp/session/modules/SessionFind.cpp:1680]: Is it not possible to determine the `encoded` status from the `encoding_` member when the `Replacer`  is constructed?

File: src/cpp/session/modules/SessionFindTests.cpp [hunk 6]
```diff
@@ -99,19 +99,52 @@ TEST_CASE("SessionFind")
       std::string line(kRegexLine);
       size_t replaceMatchOff;
 
-      Replacer replacer(false);
+      Replacer replacer("", false);
```
Comment (MariaSemple) [inline src/cpp/session/modules/SessionFindTests.cpp:102]: Should the `encoding` be the second parameter with a default value of `""`?

File: src/cpp/session/modules/SessionFind.cpp (hunk 4 above)
Comment (melissa-barca) [reply src/cpp/session/modules/SessionFind.cpp:726]: We both remove them and keep track of them. These color encodings are placed by `grep` to indicate the matched word so we keep track of where they were to tell us the location of that matched word. We remove them since they're not part of the original line.

Comment (MariaSemple) [reply src/cpp/session/modules/SessionFind.cpp:726]: What's the purpose of putting their locations into `pMatchOn` and `pMatchOff`? Is it for removing them later? Or is the `pMatchOn` right after the color open (i.e. the start of the actual match) and `pMatchOff` right before the color close?

Comment (melissa-barca) [reply src/cpp/session/modules/SessionFind.cpp:726]: As we iterate over the line's matches we are storing `pMatchOn` and `pMatchOff` so we know where the matches are so we can later replace them. At the same time we are creating a string `cleanLine` that includes everything except for the color encodings. This string gets returned in the variable the original line with the encodings was passed in.

File: src/cpp/session/modules/SessionFindTests.cpp (hunk 6 above)
Comment (melissa-barca) [reply src/cpp/session/modules/SessionFindTests.cpp]: That works, I made the update.

File: src/cpp/session/modules/SessionFind.cpp (hunk 5 above)
Comment (melissa-barca) [reply src/cpp/session/modules/SessionFind.cpp]: Good catch, fixed this.

File: src/cpp/session/modules/SessionFind.cpp (hunk 3 above)
Comment (melissa-barca) [reply src/cpp/session/modules/SessionFind.cpp:745]: Ok, updated.
